### ISSUE TITLE
Laning map shouldn't count position on paused time

### ISSUE THREAD

**Issue by vamo89** [yasp-dota/yasp#1002]
When the match is paused early on for a long time, the laning map shows the position where each hero was on paused time as the main position on heatmap. It should ignore the paused time position.

Example:
https://yasp.co/matches/2324675156/performances

In the example, the earthshaker has normal heatmap because he entered the game after the pause.

**Comment by howardchung** [comment]
Thanks.  Might need to look at this one.  My impression was that the parser should only emit one event per time (second).  Time is not supposed to increment when the game is paused.

**Comment by howardchung** [comment]
Found the bug.  nextInterval begins at 0, while time doesn't (in this case it started at 205, which is the first time value we were able to get from the replay).  Since we only increment nextInterval by 1 each time we emit entity interval data, we emitted up to 205 positions at the same time data point.
