### ISSUE TITLE
a small doubt

### ISSUE THREAD

**Issue by leovarmak** [yasp-dota/yasp#1024]
Incase I start a lobby in dota and add players manually. At last I would like to find out the winner without I manually having to watch the game. Please let me know its really important for me.

**Comment by howardchung** [comment]
I believe you can probably do this by uploading the replay to be parsed.

**Comment by leovarmak** [comment]
No other go ?

**Comment by howardchung** [comment]
@paralin or @jimmydorry might know solutions based on node-dota2 and bots connecting to the GC, but it's probably out of scope for this project.

**Comment by leovarmak** [comment]
I have been pinging all possible dota 2 repos. Thanks tho.

**Comment by paralin** [comment]
@leovarmak You won't find much success from just asking tons of people
for help. I think the best thing to do would be to examine the code and
tools available and see if you can figure it out yourself. It's pretty
easy comparatively to figure out the result of a game with a bot. You
should start by actually trying to understand how things work so that
you can come to the conclusion on how to do this yourself.
