### ISSUE TITLE
[Request] Docker-compose file for provisioning stack

### ISSUE THREAD

**Issue by mrlamroger** [yasp-dota/yasp#1063]

**Comment by howardchung** [comment]
If you want to submit a PR with this I'll take it

**Comment by mrlamroger** [comment]
I made an attempt at a docker-compose file here but didn't get it to work in one `docker-compose up` command.
https://github.com/mrlamroger/yasp/tree/docker-compose

Will want to do something like this for the DBs 
http://stackoverflow.com/questions/33309121/using-docker-compose-to-create-tables-in-postgresql-database

I'm new to my Docker on Mac Beta setup so can't verify the port forwarding and didn't look into how network_mode: host works.

I'll have more time in July. If anyone else wants to pick it up, please feel free to.

**Comment by Daerdemandt** [comment]
I've picked up where @mrlamroger left; as of [now](https://github.com/Daerdemandt/yasp/tree/docker-compose), `docker-compose up` launches minimal setup that serves webpages and parses requested matches, looks like the best thing for quickstart.

I don't really know the project in-depth so there are some things that I'm not sure of:

+ All services in one container.
This is what quickstart guide suggests and that lets pm2 control all of them at once. However, using separate containers for separate services is an option too. Is there any point though?

+ Set of services to start.
There are 2 obvious options - all services and bare minimum to have somewhat functional website (serving pages and doing backend jobs).
I suppose providing minimal working option as a default and letting user override it (via gitignored docker-compose.override.yml) is the best thing.
Again, there may be some other options and opinions I'm missing.

If nobody chimes in with some game-changing input, I'll prettify things a bit and PR tomorrow.

**Comment by howardchung** [comment]
Yeah you can split them up.  I have them all in one for less configuration.

There are a few "profiles" like `web,retriever,parser,requests` that make sense.

I do not use Docker compose myself, so this is up to you.  The pm2 way to do it is to have .json files declaring each profile.

**Comment by Daerdemandt** [comment]
> The pm2 way to do it is to have .json files declaring each profile.

I've added .json file to describe minimal configuration.

Also, some things to note if anyone is doing something similar:

 +  @mrlamroger referenced [this](http://stackoverflow.com/questions/33309121/using-docker-compose-to-create-tables-in-postgresql-database) option but there are some caveats in properly starting postgres so official image [has](https://github.com/docker-library/postgres/blob/04b1d366d51a942b88fff6c62943f92c7c38d9b6/9.5/docker-entrypoint.sh) special way of supplying sql files for init.

 + If you are changing files that go into image at build stage, make sure that old Docker image is removed instead of being reused to create new container. Wiping old containers and images at every test is foolproof and can save you some debugging.

+ `create_tables.sql` assumes that we are already using correct database (hence it's invoked with `psql -U postgres `**`yasp`**` < sql/create_tables.sql`). However, postgres image init process knows nothing about yasp database and sql file should select it. I don't know how `create_tables.sql` is used in other peoples' setups so I haven't changed it - instead, its copy in container gets prepended at build stage.

PR incoming.
