### ISSUE TITLE
Match table empty/missing matches

### ISSUE THREAD

**Issue by adamrisser** [yasp-dota/yasp#1071]
Hi,

I am getting a blank match table. It was working for me last night (checked around 9pm), but now the table is blank (though my estimated mmr is still populated).

https://yasp.co/players/138717042

Expected Migration Completion Date
----
2016-06-26

**Comment by Stereo8** [comment]
Same, all of my matches just disappeared. 

https://yasp.co/players/113103177

**Comment by vhpanisa** [comment]
Same here

https://yasp.co/players/76746965

**Comment by howardchung** [comment]
Sorry everyone, I messed up during the transition.

Post-Mortem
----

What happened:
Originally we ran Cassandra in Docker without an external container storing its persistent data.  This is fast and easy, but means that if you remove the container the data is deleted as well.  One of the things I moved last night was putting Postgres/Redis on their own instances to avoid the OOM errors we've been seeing lately.  I accidentally issued `docker rm -fv cassandra` instead of `docker rm -fv redis` while trying to clean up the old containers, taking out half the data.

Mitigation:
I started up a new cluster (this time mounting separate persistent disks to `/var/lib/cassandra` to hold the data).  I took a snapshot of the postgres DB before I started, so I'm using that to re-do the migration.

Impact:
It will take about 4 weeks to move all the matches again.  Everyone will see matches missing until this is complete.  I turned off writing to Postgres about a day before this happened, so about a day's worth of matches will be missing.  They can be requested by ID if desired. (approximate range is 2410000000 to 2418000000).

Cost:
I created a new standard-4 instance, 10TB HDD, and highcpu-16 preemptible instance to redo the migration.  It'll probably cost an extra $650 or so this month.

**Comment by adamrisser** [comment]
oof, i'll be sure to donate some cheese. I really appreciate what you guys do.

Side question: Do you guys enjoy docker? Its something I have been investigating for some time. Do you think its been worth it using?

**Comment by howardchung** [comment]
I like Docker a lot, but it does lose some of its advantages in the cloud environment since it's so easy to delete and recreate instances already.

* Less overhead than VMs (but in the cloud you're running on top of a VM anyway)
* Easy to run multiple DBs/swap versions in dev
* Ensures dev matches prod

**Comment by adamrisser** [comment]
We run on AWS, so that is very helpful, thank you.

**Comment by howardchung** [comment]
I'll keep this updated occasionally:

https://docs.google.com/spreadsheets/d/1N62hPh21S8BgCU6DQbqw6dffMDMW1GGVggBrTVsaG5M/edit?usp=sharing

**Comment by ptqa** [comment]
>Originally we ran Cassandra in Docker without an external disk storing its persistent data. 
>I accidentally issued docker rm -fv cassandra 

![LOL](https://raw.githubusercontent.com/jglovier/gifs/gh-pages/lol/milk-out-noze.gif)

Man, your service is good, but plz don't use docker for databases (even with volumes). Better way to manage this kind of application is configuration management system.

**Comment by howardchung** [comment]
Example?

**Comment by ptqa** [comment]
Like ansible (simpliest one), chef, salt, etc.

There are ready modules for cassandra, redis and postgresql:
* ansible (https://github.com/Kami/ansible-cassandra https://github.com/DavidWittman/ansible-redis https://github.com/ANXS/postgresql)
* chef (https://supermarket.chef.io/cookbooks/cassandra https://supermarket.chef.io/cookbooks/redis https://supermarket.chef.io/cookbooks/postgresql)
* etc.

**Comment by howardchung** [comment]
19% done after about 4 days.

**Comment by howardchung** [comment]
44% done after 9 days

**Comment by howardchung** [comment]
68% done after 14 days

**Comment by howardchung** [comment]
82% done after 17 days

**Comment by howardchung** [comment]
Around 96%.  Will likely take 2-3 more days to finish the batches (16 done, 9 remaining)

**Comment by howardchung** [comment]
We're done! yay!

**Comment by Stereo8** [comment]
Finally! Great
