### ISSUE TITLE
Parse All

### ISSUE THREAD

**Issue by Zalitan** [yasp-dota/yasp#1184]
Hello, is there a way to parse all non-bot matches from 2 months ago to today or get a full history in general? The two months ago data starts with http://www.dotabuff.com/matches/2450907147 match ID 2450907147.

**Comment by Zalitan** [comment]
Yasp player ID https://yasp.co/players/94554734  .

**Comment by howardchung** [comment]
Are you asking for basic API data, or replay parsing?

If you just want basic data (i.e., the matches aren't showing up at all right now), then this is because you were probably anonymous.  If you give your account_id I can run a scan to fill in the gap.

If the matches are there but just don't have detailed data, unfortunately Valve deletes replays after 10 days so this will not be possible for all of them.  You can use the request form to manually request the ones that have not expired.

**Comment by howardchung** [comment]
I see that there are matches from more recent than 2 months ago and that almost all are parsed.  Is there something else you're looking for?

**Comment by Zalitan** [comment]
Yes, there are some matches however most are not showing up. Only some have been recovered, for example ( I want to transfer mainly from Dotabuff to yasp) on http://www.dotabuff.com/players/94554734/matches?date=all&enjoyment=any&page=2&timezone=America%2FChicago 
there are match data that does not show up on Yasp.

**Comment by howardchung** [comment]
Ran the scan, numbers look comparable now.
