### ISSUE TITLE
Enabling Match-History (without parsing?)

### ISSUE THREAD

**Issue by DarkMio** [yasp-dota/yasp#136]
I guess this is more endorsed and I would highly rate this feature:

Enabling a match-history, which doesn't need to be parsed, but is in general useful (especially for your hero-count on your own profile).

I know of the limitation of the SteamAPI in that regards, solution is simple: Iterate over all entries of said SteamID per Hero-Bases. You can get all data, as long as they do not have 500+ games with one particular hero - which is very unlikely. If you want, I can plug you some python-sample-code I've written a while ago.

**Comment by howardc93** [comment]
Hmm, this is an idea we haven't considered.  

We do have code in place to get full match history, example: http://yasp.co/players/88367253

However it puts heavy load on Dotabuff since we get all of a user's match_ids from there, so we haven't scaled it out to every user.

We might be able to get more match history with this idea, but it will still have to be done over a period of time, since we have to make a call to getMatchDetails for every single match.

**Comment by DarkMio** [comment]
Why even using Dotabuff? SteamAPI is sufficient, you just run it per user, get 500 entries max and be happy. As MatchIDs are in ascending order, you can even sort it easily in any kind of database, if you really have to.

**Comment by howardc93** [comment]
Yeah, this is a more scalable option that we might be able to apply to all users.  I'll look into it.

**Comment by DarkMio** [comment]
This is a possible solution in Python, should be easy to port: https://github.com/DarkMio/Dota2RecordService/blob/master/stats_service.py

It scales well, might need a FIFO-queue for the database with multiple-threads. It builds up a list of latest heroes and then iterates over the API. Feel free to port it for you, as it is way better than scraping it off dotabuff (don't do that. :( )

**Comment by howardc93** [comment]
Code for getting "full" history from webapi is there.  At this point we're not going to get everyone's full history though, since it would take a lot of time and requests.  Perhaps we'll do it bit by bit.
