### ISSUE TITLE
Kills in detail view not always showing?

### ISSUE THREAD

**Issue by DukeHarris** [yasp-dota/yasp#153]
In [this](http://yasp.co/matches/1177097315) match, I was witch doctor and had 4 kills (which is shown on the overview page).
However, on the [Details](http://yasp.co/matches/1177097315/details) page the last column (kills) is empty for the witch doctor row. Shouldn't there be pictures of the enemies killed like in the other rows?

**Comment by howardc93** [comment]
Yes, the kill counts can be off since Dota's score system doesn't always reflect exactly what's in the combat log (which is what the parser uses).

When creeps, towers, controllable units, or illusions get the kill, the combat log will report the exact unit that actually did the fatal damage, but Dota may award the kill to a hero.

In the case of controllable units/illusions, this could probably be remedied somewhat by proper merging of unit blocks in the parsed data (such as NP treants with NP), but this also opens up other issues (mainly Rubick stolen skills can overlap with this, as can "everyone" items like Necronomicon.

However, for creep/tower kills, I believe Dota awards the kill to a hero if it did damage to the victim within something like 20 seconds.  This would have to be detected on the parser end.

It's a sticky issue, and PRs to help improve the displayed stats are welcome.

**Comment by DukeHarris** [comment]
It looks like there is a general issue with witch doctor. In [this](http://yasp.co/matches/1179319112/details) game it's the same. Maybe there's something wrong with how Death Ward kills are tracked?

**Comment by howardc93** [comment]
implemented a improved merging function in #162 to help account for unit kills.

Won't know if it helps until it's deployed to production though.

**Comment by howardc93** [comment]
If you want to check one of those matches, re-upload the replay and it will be re-parsed.

**Comment by howardc93** [comment]
Scratch that, fixed the issue in development.

Edge cases are witch_doctor and shadow_shaman, since I try to split the string up by "_", and match the third entry to a hero name.

Push should be going out to production soon and this merging is done on page request, so you don't need to reupload the replay.
