### ISSUE TITLE
Invalid ability icon when leveling subabilities

### ISSUE THREAD

**Issue by chudooder** [yasp-dota/yasp#301]
If a user levels up a subability such as Launch Fire Spirits, the icon of the ability is not displayed and is instead replaced by a number.

![image](https://cloud.githubusercontent.com/assets/1715129/6571495/f57f4670-c6d6-11e4-92c7-6ee36531dc3d.png)

**Comment by howardc93** [comment]
I caught this one and fixed in dev branch:
https://github.com/yasp-dota/yasp/blob/dev/sources.json#L948

We've scheduled our next deployment for 3/21, and this should be going out then.

Thanks for catching this, and let us know if you find another one.  We have to manually map every number to an ability, so there are probably a few gaps.
