### ISSUE TITLE
Tower damage calculation might be incorrect

### ISSUE THREAD

**Issue by evaryont** [yasp-dota/yasp#305]
Another parsing bug I think I found in the match I mentioned in #304, [match 1318351122](http://yasp.co/matches/1318351122).

At 12 mins, 57 seconds into the game Witch Doctor does an auto-attack to the Tier 1 Bottom tower on Radiant's side. Dotabuff & Yasp both report he did only 6 damage total to towers, but looking at the replay it seems incorrect.

Using the formula for armor from [the Dota2 wiki article for armor](http://dota2.gamepedia.com/Armor#Damage_reduction.2Fincrease) (the additional division is because towers have a 50% resistance to hero damage, per the wiki):

    ((1 - 0.06 × 20 ÷ (1 + 0.06 × |20|)) * 74 ) ÷ 2

Results in about ~16.81 damage which is in line with what I saw watching the replay myself. But is higher than what both sites report.

Of course, if this is the wrong place to report these bugs, feel free to mention it.

**Comment by howardc93** [comment]
Here's the relevant entry from the combat log:
{"time":961,"type":"damage","unit":"npc_dota_hero_witch_doctor","key":"npc_dota_goodguys_tower1_bot","value":17,"target_hero":false,"target_illusion":false}

So the replay parse does track the correct amount of damage done, but the number reported in the WebAPI appears to be off for some reason.

Closing since this isn't an issue with the parser.
