### ISSUE TITLE
Parsing is skipped if another user in the game is inactive

### ISSUE THREAD

**Issue by somesmart** [yasp-dota/yasp#327]
I played a game last night and the parsing was skipped:

http://yasp.co/matches/1349359522

I've been logging into yasp daily, so I'm thinking it may have been skipped because another player in the game has been inactive: 

http://yasp.co/players/72704227

Is this intended behavior?

**Comment by sar3th** [comment]
I've had a similar problem with these matches:
http://yasp.co/matches/1343720875
http://yasp.co/matches/1343783608
They were skipped even though I was an active user on that day. I also assumed that it's caused by an inactive user. It als happened to a match where I don't have the matchid of that took place yesterday...
A temporary workaround for users is to use the [request page](http://yasp.co/request) to manually add them to Queue.

**Comment by albertcui** [comment]
Not at all intended! That is for the heads up. We'll try to fix this asap.
You can request the match to get it parsed. yasp.co/request

**Comment by albertcui** [comment]
Sorry for the bug! 😕

**Comment by somesmart** [comment]
No problem, thanks for the great site!

**Comment by howardc93** [comment]
```
    async.each(match.players, function(p, cb) {
        if (p.account_id in activePlayers) {
            //skipped
            match.parse_status = 3;
        }
        if (p.account_id in trackedPlayers) {
            //queued
            match.parse_status = 0;
        }
```

lol I'm bad at code:
match.parse_status is getting set to the state of the last player in the match.  Need to add a check so we don't overwrite a 0 with a 3.

I really should add unit tests for the sequential/add new matches code.
