### ISSUE TITLE
biggest throw/comeback/stomp/stomped

### ISSUE THREAD

**Issue by Brian-McG** [yasp-dota/yasp#344]
So now that 1st April is over, I think its something that should actually be added.
Possibly keep track of the losing team's biggest gold and/or exp lead vs the gold and exp near the end? 
Could also check if losing team losses with a large difference in gold and exp in their favor (10 - 15k +)
It's not easy to boil it down to a number but you can start with a simple metric and build it up over time.

**Comment by howardc93** [comment]
@albertcui wanted to try to do something with this

**Comment by howardc93** [comment]
If we're gonna do this, I think we should have a separate page for all these "fun" stats computed using some arbitrary formula

**Comment by howardc93** [comment]
The metric we will probably use:

For each match, find the winning team and check the gold/xp advantage every minute.  The "throw" level is the maximum disadvantage that the winning team had.

**Comment by howardc93** [comment]
As part of computematchdata we compute the "throw/comeback" factor.  This is a player-specific value.  We iterate through the gold advantage chart and determine the largest negative/positive values of the winning team.

negative: biggest comeback for this player's team
positive: biggest throw for this player's team

**Comment by howardc93** [comment]
After suffering a 22.3k throw, I did some thinking about this:

To compute this we require parsed data from all 10 players in a game.  This is because we need to sum the gold/xp of each player to compute the radiant advantage at each minute.

Now, we can do this with individual matches since we retrieve the full match in this case.

However, when we aggregate matches (such as for an individual player), we only retrieve the parsed data for a single player.  This is necessary if we want to compute the "biggest comeback/throw" record for each player.

Solutions:
1.  We can retrieve full parsed data for each match.  This has the potential to be slow, since a match is ~200kb and a player can have potentially thousands of parsed matches, meaning we get bottlenecked by HDD transfer speed.

2.  We can compute the summed radiant advantage at insertion time and store it in match.parsed_data.radiant_gold_advantage as an array.  We would need to run a migration to "back-fill" this data for existing parsed matches.

Given this array of radiant_advantage, we can then compute four values per player_match:
```
throw: match.radiant_win !== isRadiant(player) ? (isRadiant(player) ? max(radiant_gold_advantage) : min(radiant_gold_advantage) * -1) : 0
comeback: match.radiant_win === isRadiant(player) ? (isRadiant(player) ? min(radiant_gold_advantage) : max(radiant_gold_advantage) * -1) : 0
loss: match.radiant_win !== isRadiant(player) ? (isRadiant(player) ? min(radiant_gold_advantage) : max(radiant_gold_advantage) * -1) : 0
stomp: match.radiant_win === isRadiant(player) ? (isRadiant(player) ? max(radiant_gold_advantage) : min(radiant_gold_advantage) * -1) : 0
```
Then for each player we take the max of these values in order to find records.

**Comment by howardc93** [comment]
While we do this we may as well compute pick order, since this also requires data from all 10 players.
