### ISSUE TITLE
Track total Gold Earned/Spent over lifetime

### ISSUE THREAD

**Issue by McHearty** [yasp-dota/yasp#345]
Should be pretty simple to impliment, thoughts?

**Comment by howardc93** [comment]
Doable, but not very useful IMO

**Comment by howardc93** [comment]
@albertcui ?

**Comment by McHearty** [comment]
@howardc93 useful enough to be a socketable gem people pay money for, and is an interesting stat to track

**Comment by howardc93** [comment]
I'll leave it to @albertcui  to decide.  Or if you really want it you could submit a PR.  It would probably go on the trends page under the records section, and the summing of stats is done in advquery.js's aggregator function.  In fact I'm already computing sums for all of those stats, that's how we get the average.  We're just not displaying the sums cause most of them are pretty pointless (how many kills, deaths,assists lifetime, etc.)  Gold is just a bit trickier since you have to multiply gpm*duration (the "gold" field is how much gold you had left at the end of game)

**Comment by howardc93** [comment]
Dumping the data in the table.  Hopefully it doesnt look too messy. . .
