### ISSUE TITLE
relative magnitude within columns

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#405]
We should make a class for columns where we show the magnitude of each cell, relative to the local max (the largest value in the column has a bar 100% width, scaling down)

**Comment by howardc93** [comment]
This should be implemented using pure JavaScript (not in jade), so we can use it for both datatables and jade-rendered tables.

**Comment by howardc93** [comment]
might be tricky with non-numerical columns (duration?)

**Comment by howardc93** [comment]
An alternative scheme is to shade the table cell darker/lighter based on the value.  This would use mostly the same code.

**Comment by howardc93** [comment]
solutions for looping through table by column:
http://stackoverflow.com/questions/6917143/loop-through-the-cells-of-a-columns-not-cells-of-a-rows-with-jquery-or-js-on

**Comment by howardc93** [comment]
probably easiest to compute this server-side and add it to the data, then render the actual results using JS on the client side.

**Comment by howardc93** [comment]
I doubt nick wants to do this so I will reassign it

**Comment by howardc93** [comment]
giving to albert since he has ideas on what columns it works best on

**Comment by howardc93** [comment]
There are arguments for doing it both ways:

Client side:
We'd probably want to have jade render out the match tables then call datatables on it.  This would require us to dump some of the formatted data (like duration and end time) so that the sort can work properly.  Then we iterate through the table by column and compute the lengths.

Server side:
We need to find the backing array behind each table we draw and iterate over them twice for each column that needs to have magnitude shown, once to find the max and once to add the proper width to each element.

**Comment by howardchung** [comment]
I think given the current state of the code, server side makes more sense, but I don't know if there's a more elegant solution then having to call a function for each column of each table that we want to display this for.

**Comment by Iparke** [comment]
Am I understanding what this looks like?

![image](https://cloud.githubusercontent.com/assets/11266229/9558166/45492788-4d97-11e5-852d-c4af168f7615.png)

**Comment by howardchung** [comment]
Yeah something like that.  Dotabuff does this for some columns.
