### ISSUE TITLE
Teammates table incorrectly counts enemies

### ISSUE THREAD

**Issue by LewisJackson1** [yasp-dota/yasp#457]
[My Profile](http://yasp.co/players/47499620) incorrectly shows [this user](http://yasp.co/players/24622539) as having an 100% win rate over 4 games with me as a team mate. We have had 4 games together, however two of them are as a team mate and two as an enemy. Proof: http://www.dotabuff.com/players/24622539/me

**Comment by howardc93** [comment]
This is likely due to #448 .

We should be deploying new code tonight that fixes the problem, will check this afterward and see if it's fixed.

**Comment by howardc93** [comment]
Actually, after a second look:

The data is correct, but I can see why it can be confusing.  Since we added "played against" as well as "played as teammate", the "Matches" column now shows the total number of games with.  So this player has played 4 games with you, 2 as opponent and 2 as teammate.  You won all of them.

I'll see if I can do something to make it more obvious.

**Comment by LewisJackson1** [comment]
The data is fine then, but the table is titled "Teammates", which is incorrect.

**Comment by howardc93** [comment]
In https://github.com/yasp-dota/yasp/commit/f10ac4d7d4a0968fc15744bcf208c6d401310384:

I changed the title to Teammates/Opponents

**Comment by LewisJackson1** [comment]
That is really not an appropriate solution. That data is useless, why does it show? It needs to, at the very least, show how much games they were an opponent and how much they were a team mate. Ideally it would be the same as DotaBuff - where two tables show the teammates stats and the opponents stats.

**Comment by howardc93** [comment]
It does, those are the other two columns.

The first is the total, the second is the teammate count, and the third is
the opponent count
