### ISSUE TITLE
Pick order in captains mode

### ISSUE THREAD

**Issue by Erk-** [yasp-dota/yasp#474]
Pick order does not work correctly in captains mode.

Eks. http://yasp.co/matches/1556597622/details says Meepo was picked first but he was picked second last
![](https://cloud.githubusercontent.com/assets/3659684/8184090/cdf97504-143c-11e5-87be-6f7a1991ace6.png)

**Comment by howardc93** [comment]
This is because pick order and drafting is separate.

If you want the drafting picks/bans, look in the "Basic" tab.  This data is available from the API: http://yasp.co/matches/1556597622/

The pick order is obtained by parsing the replay and is the order in which the player "selected" their hero (which in CM occurs at the end of the draft).
