### ISSUE TITLE
Parsed matches are re-parsed when requested via Request page

### ISSUE THREAD

**Issue by lomash** [yasp-dota/yasp#498]
If a match that has already been parsed is entered at the Request page, I believe it is re-parsed.

Shouldn't it just redirect the user to the match page?

**Comment by lomash** [comment]
I tried requesting an expired game and the status of this game is now set to Unavailable.
http://yasp.co/matches/1560907404

If a game whose replay still exists is requested, the status is changed to Queued and after a minute, Parsed.

**Comment by howardc93** [comment]
The reason we have it reparse is to allow users to "update" the data on an older match if we update our parser to output more data.  I'm thinking about not re-parsing matches though, since it only covers 7 days.

There is supposed to be a check for not setting already parsed games status to 1 (unavailable) if the match already has a non-zero parse status.  Seems like there's a bug though.

The third case behaves as expected.  When we get a request we first hit the API to get the basic match data, set status to queued, and update the DB.  Then the match is parsed and we set the status to parsed.

**Comment by howardc93** [comment]
changed check to not mark matches unavailable if they already have parsed data.

I don't think we're going to go through and correct all the db entries that got accidentally marked as unavailable though.
