### ISSUE TITLE
Pages still load very slowly

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#520]
hi,
The update box currently states that player pages should now load faster, I can't confirm this.
As a test I just measured the time it took to load http://yasp.co/players/157506503/matches and got 42 seconds.
The only thing I really noticed is that recent games take a while to show up on the overview/matches page. Is that due to the dota api being slow or a new cache?

**Comment by howardc93** [comment]
* The initial load builds a cache.  This initial load can (right now) be really slow.
* The matches page is never cached.  This is because it requires displaying all of a user's matches, rather than just aggregations across the data, which are relatively small.
* Using a filter option means our cache is invalid, so using a filter on any page will lead to slower loads.
* We're thinking about upgrading our HDD in the next few days to increase throughput limits.
* We had an issue earlier that means we're about an hour behind on new matches.  This should be resolved soon as we catch back up.

**Comment by howardc93** [comment]
I rewrote the caching to cover all player pages.  They should (including the matches tab) now all load quickly after the initial caching load.
