### ISSUE TITLE
PostgreSQL migration/engine upgrades

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#582]
A relational DB is probably a better option for Dota match data.

Something we could play with/try out if somebody wants to take the time:

Checklist moved to PR

**Comment by Aehrraid** [comment]
Why should SQL be faster than Mongo?

**Comment by howardchung** [comment]
Some of the queries we do don't work that well with NoSQL.  It may not be a huge performance impact, but sometimes I'm finding myself having to write complex JavaScript to get data (such as player/hero teammates/opponents).

Aside from that it would just be for fun/interest though.

**Comment by Aehrraid** [comment]
Ok, sounds legit. I've overseen the aspect of 'play with/try out'.

**Comment by gortiz** [comment]
Hi there,

I am a enthusiastic dota player and the main developer of [ToroDB](www.torodb.com), an open source database that "talks" the MongoDB protocol but stores the data on SQL databases (only PostgreSQL is supported right now, but new db will be supported in future).

ToroDB is a software under development, it does not support all MongoDB options yet... but we are working on that. We are also looking for projects that uses MongoDB to test our implementation and I really like your stack. I am sure ToroDB is not going to be able to replace MongoDB on YASP stack because we do not support some things you are using (for example, we do not implement queries with javascript yet) but it can be fun to try it. For example, one of the use where ToroDB excels right now is one that @howardchung talked about: if you want to move from "schemaless" world to a SQL world you need to design your schema and that can be error prone (you can forget something, etc). On ToroDB we automatically classify documents into what we call "structures" (you can see our documentation to know what I am talking about) and these structures can be used to know rare cases that are not easy to see when you are creating your schema "on your mind". In fact we used ToroDB to successfully migrate some projects. There is feature we are trying to implement that will allow our users to make queries on an easy to write SQL that will be executed against the data they stored using MongoDB protocol, so you can use both worlds at the same time.

If you want to try it, you can use mongoimport or mongorestore to import some data on ToroDB. It would be easier to plug a ToroDB instance as a secondary on the MongoDB replication set, but at this moment we do not support replication. The first ToroDB version that will support that will be released not later than early October. I will be pretty busy until we finished this feature, but I will be very happy to help you if you want to try ToroDB.

**Comment by howardchung** [comment]
@gortiz I think if we migrate we'd just use PSQL directly with pg/sequelize for JavaScript bindings, rather than needing to run an intermediate dependency.  Thanks for telling us about ToroDB though--it sounds like a cool idea!

**Comment by howardchung** [comment]
Other reasons for migration:

* I like knowing exactly what fields we have available.  It can be a terrible time when a certain match is in some format we don't expect.
* Messy structure.  This could probably be improved without moving from MongoDB, but it's going to involve messing with a lot of data anyway, so why not bundle it with the migration?
  * All parsed data goes under match.parsed_data.  The idea was that we can "reset" a match to unparsed status simply by unsetting that key, but in practice it's not really useful.
  * parsed_data contains a player array of 10 parsed players.  A common use case is trying to extract a record for a player_match (one player's performance within a match).  However, MongoDB doesn't allow us to slice into two separate arrays within a document.  This means we have to resort to annoying workarounds:
  * Request the entire parsed_data blob and pick the player we want.  Very expensive in terms of I/O.
  * Query for the matches without parsed_data, then make a second pass through and slice into the parsed_data.players array for just the one player we want.  This is what we're doing now, and it's probably unnecessarily slow.
* Storage improvement?  MongoDB by its nature requires us to store key names with each document.  This is a lot of overhead, and while WiredTiger's native compression helps a lot (factor of 3), it may still be more space efficient to use a relational DB.

**Comment by gortiz** [comment]
I think you are right. If you can use SQL directly, you dont need ToroDB.
But it could be useful on the first stages if you dont know all possible
combinations of fields on documents. ToroDB is useful in that case because
it automatically analyze your documents and creates tables to store them. I
am sure you can improve the table desing and even better, once you have all
SQL and transactions, you can modify YASP to use documents in a different
way. You can normalize things, remove duplicates, etc. So ToroDB isn't
going to create the tables for you, but the tables it creates can be useful
to get the knowhow of your system or to find something you didn't realize.

Talking about the messy structure... of course MongoDB makes too easy to
make this kind of messies. In the case you are talking about i think you
can slice the array if you modify its contente. Lets say your documents are
like:

{
>     match: {
>
                anotherField: "whatever",
>
        parsedData: [
>             {player: 1, data: "whatever1"},
>             {player: 2, data: "whatever2"},
>             {player: 3, data: "whatever3"},
>             {player: 4, data: "whatever4"},
>             {player: 5, data: "whatever5"},
>             {player: 6, data: "whatever6"},
>             {player: 7, data: "whatever7"},
>             {player: 8, data: "whatever8"},
>             {player: 9, data: "whatever9"},
>             {player: 10, data: "whatever10"}
>         ]
>     }
> }
>

You can execute the following query:

db.test.find({"match.parsedData": {$elemMatch: {player:
> 2}}},{"match.parsedData.$": 1})


It returns the following:

{ "_id" : ObjectId("whateverId"), "match" : { "parsedData" : [ { "player" :
> 2, "data" : "whatever2" } ] } }
>

It has some boilerplate (the _id, that can be removed and the path
match.parsedData) but it could be acceptable.


On the other hand, if you talk about storage... you are right. Yeah,
WiredTigers doesnt eat as many bytes as mmapv1 *on disk* but it is as bad
as mmapv1 on cache, because the compression is done when it is flushed to
disk, but on RAM pages it similar to the older storage engine.

In brief:

   - If you want to use SQL, go ahead, I think it is the best way to store
   your data.
      - If you want to use all the power SQL gives you, you may need to
      modify YASP a lot (I am not familiar with the code... yet! ;-) )
      - If you dont want, you may be interested on import some data on
      ToroDB just to see the tables it creates. It could help you to find cases
      you wouldn't aware off.
   - If I understood you correctly, you can do what you want with MongoDB,
   but I still recommend you to migrate to SQL. I would like to help you with
   that, but I'm afraid I will not have time until November.
   - MongoDB is horrible on memory usage.


2015-09-24 9:15 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
Yeah, I think I've got a pretty decent design sketched out, but feel free to look it over and comment:

Schema:
https://github.com/yasp-dota/yasp/blob/sql/migrations/create.sql

Migration script to move everything over:
https://github.com/yasp-dota/yasp/blob/sql/migrations/sqlMigrate.js

Re: Mongo slicing: Yes, we can slice into the match.parsed_data.players array, but the problem is doing it at the same time as slicing into match.players.  We have to make two passes, one for match.players and one for match.parsed_data.players.

Early tests on my devbox indicate even more space savings for PSQL compared to mongodb, so that's good.

**Comment by gortiz** [comment]
I will check it.

Talking about space savings... We are saving like 50%-80% on disk usage with ToroDB using a not optimized schema, so I am sure sure an optimized design will be even better (and cheaper on CPU cycles!). It is not easy to know the improvement on memory, but I am sure it will be massive too.

**Comment by howardchung** [comment]
question for @gortiz or any other PostgreSQL experts:

If I do a projection that only needs columns from one table in a query that joins two tables, is the optimizer smart enough to skip the join?

**Comment by gortiz** [comment]
I bet it is smart enough, but the best thing to be sure is to try it. You
can use *explain analize* on a query and then copy and paste the result here
<http://explain.depesz.com/>. It will tell you A LOT of useful information

2015-11-30 5:00 GMT+01:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
For the first:
```
yasp=> explain analyze select duration from matches left join match_skill on matches.match_id = match_skill.match_id where matches.match_id = 1946654928;                                                     
                                                      QUERY PLAN                                                       
-----------------------------------------------------------------------------------------------------------------------
 Index Scan using matches_pkey on matches  (cost=0.28..4.30 rows=1 width=12) (actual time=0.031..0.031 rows=0 loops=1)
   Index Cond: (match_id = 1946654928)
 Planning time: 0.775 ms
 Execution time: 0.105 ms
(4 rows)
```

For the second:
```
                                                         QUERY PLAN                                                          
-----------------------------------------------------------------------------------------------------------------------------
 Nested Loop Left Join  (cost=0.43..8.48 rows=1 width=8) (actual time=0.008..0.008 rows=0 loops=1)
   Join Filter: (matches.match_id = match_skill.match_id)
   ->  Index Scan using matches_pkey on matches  (cost=0.28..4.30 rows=1 width=12) (actual time=0.008..0.008 rows=0 loops=1)
         Index Cond: (match_id = 1946654928)
   ->  Index Scan using match_skill_pkey on match_skill  (cost=0.15..4.17 rows=1 width=12) (never executed)
         Index Cond: (match_id = 1946654928)
 Planning time: 0.179 ms
 Execution time: 0.050 ms
(8 rows)
```

So it does look like it is skipping the join.  The reason I'm asking is that I'm wondering if it allow postgres to more efficiently use the cache if we split up the parsed_data into separate tables.  Then queries that project only based data columns (like the Overview) wouldn't load the parsed data into memory.

**Comment by gortiz** [comment]
Theorycrafting, it should. Big values should be toasted (the automatically
compression system PostgreSQL uses) and they shouldn't be decompressed when
they are not used, but if I remember correctly, there are several jsonb
document values on these rows. If some of them are not toasted (it could
happen if they are not big enoght) they will be stored on the same memory
page than the others (the "useful" columns) so they will be occupying space
on the cache.

I would also recommend to execute analyze
<http://www.postgresql.org/docs/9.1/static/sql-analyze.html> if you didn't
execute it yet. Autovacuum should execute it, but it is useful to manually
execute it when a lot of data has been imported (as you did when you
migrate from mongo)

2015-11-30 11:50 GMT+01:00 Howard Chung <notifications@github.com>:
