### ISSUE TITLE
more informative request form error messages

### ISSUE THREAD

**Issue by mbax** [yasp-dota/yasp#698]
The message doesn't indicate if it's a failure between me and yasp, or yasp and something else (yasp to yasp, yasp to valve, etc), which could be improved.

I am getting this when attempting to request parsing a match from 17 hours ago that didn't get parsed (perhaps during the lost 4 hours the heading mentions?) as well as a match from 3 hours ago.

![image of failure](http://i.imgur.com/ufKpzQH.png)

**Comment by howardchung** [comment]
Yeah, I realize the error message is often unhelpful.  The reason is because right now what happens when a match ID is entered:

* Request basic match data from Steam API.  We may or may not have the match, but we request the latest data and save it anyway.
* This is a request, so we always send it on to the parse step.  We get the replay salt/URL and save that to database (if it didn't exist already)
* We do a GET request from a random parse worker and await the JSON response with parsed data.
* Save the resulting parse data to database.
* On the client side the browser is polling for the status of the job.  If the job.error field exists, we display th error.  If the job disappears, we assume the job completed and redirect to the match page (based on the entered ID).

I think what happens is that the parse workers may not all be up.  If we select one that is down, the returned error will be ECONNREFUSED and this bubbles back to the user.  You could retry and see if you can get one that is active.

In #582 I implemented distributed parse clients (where the parse workers request jobs from the queue rather than yasp-core trying to request parses from servers).  I don't know if it will help, but it should avoid the issue of trying to parse replays on unavailable nodes.

**Comment by mbax** [comment]
I've now failed four times on the same match ID (1838492996). Takes what feels like a minute each time.

**Comment by howardchung** [comment]
Looks like replay is unavailable:

http://replay111.valve.net/570/1838492996_1042120220.dem.bz2

Getting a 404 error.  I think the parse node is supposed to send the 404 back to the client so we can display it, but maybe something is going wrong...

**Comment by howardchung** [comment]
I did some work to get the error message to show up properly in the browser after a failed parse in `sql` branch.  I don't know exactly when we're launching that in production though.

**Comment by howardchung** [comment]
We could still probably do some work to make the error messages more informative.  A short list of things that could go wrong:

* 404.  Replay not found.  This can happen if trying to request too soon after a match (not available yet) and after the replay expires (7 days or so).  The parser will actually send back any non-200 error code as an error, but in practice 404 is the main one that we see.
* "incomplete".  Parser crash, or something that caused the parse not to complete properly.  `parser.js` sets a default error message of "incomplete" and sets it to null when we encounter the epilogue at the end of the replay.
* ECONNREFUSED.  Probably means we're trying to connect to an inactive parse worker.  Since right now we just list all of the parsers in our config, we can still try to use them when they go down.
* socket hang up.  This probably means the connection was lost while waiting for JSON response from parse worker.  Could happen if the process crashed due to restart or an unhandled exception.

**Comment by howardchung** [comment]
I added a friendlier error message that asks users to make sure the replay is available in client.  This is probably the most common source of error.
