### ISSUE TITLE
Game where every enemy abandoned is counted as loss

### ISSUE THREAD

**Issue by GIider** [yasp-dota/yasp#724]
For shits and giggles I requested a parse of a game where everyone except me abandoned: http://yasp.co/matches/1898847061

Weirdly enough if I check my match stats yasp reports the game as a loss even though it was Dire Victory: http://yasp.co/players/39088211/matches?hero_id=84&isRadiant=0&win=0

**Comment by howardchung** [comment]
The condition for determining the dire/radiant win is isPlayerRadiant (player_slot < 64) === match.radiant_win.

It looks like for this match radiant_win is undefined.  So the equality check doesn't pass.

For the match display we just check if match.radiant_win, so undefined evaluates to false and so we show "Dire Victory".  If you were on Radiant it would have shown up as Dire Victory anyway.

Not really sure how best to handle this case.  It seems kind of edge-case, I'm surprised it showed up in the API at all.

**Comment by GIider** [comment]
I would agree that matches like this should simply not be counted at all. Since you have to manually parse it to have it show up on your profile you could simply refuse it on the parse screen if you detect junk values like that

**Comment by howardchung** [comment]
Oh, good point.  So it didn't show up in the sequential API as expected, but can still be requested.  I could add that check pre-insertion.

**Comment by howardchung** [comment]
I am just going to add it as a condition of being a "significant" match that match.radiant_win !== undefined.

I don't want to mess with the insertion code because if I handle by:
* throw an error, then if for some reason the sequential API has a match without radiant_win then it will get stuck retrying
* do nothing but act like it succeeded, then the request will attempt to visit the match page and throw 404/500 because the match cannot be found
