### ISSUE TITLE
Change probabilty-based cache invalidation to a deterministic solution

### ISSUE THREAD

**Issue by mhartkorn** [yasp-dota/yasp#740]
https://github.com/yasp-dota/yasp/blob/502fbe01d964240d9af394a283be200f446abc52/routes/players.js#L284

This line creates inconsistent behavior and might lead to severely outdated caches if the random() function produces a sequence of unlucky numbers. This doesn't really matter in this case but I don't really like code like this. If it should matter sometime later, and somebody forgets about this, it might lead to confusion.

To solve this, I would propose to write the absolute number of matches a player has played into the database and query it. This also get rid of the `count('match_id')` operation, which costs a lot of resources if used excessively (currently on each player page load, as far as I can see). Does someone have a few statistics about how fast `SELECT COUNT(match_id) FROM player_matches` runs? I don't know how much data is in the production tables right now but I think it is one of the reasons yasp.co is a bit slow at the moment.

The implied meaning of numbers (`count === 0` is always invalid) should be avoided and be replaced by a parameter in the callback function. E.g. `cb(err, count, cacheValid)`.

**Comment by howardchung** [comment]
Yeah, I don't like it either.  The original code checked on every load but it seems that count() is relatively slow.  I was hoping it would be fast enough since we're not counting the whole table but cutting down the size via account_id filter first (so realistically there will never be more than ~15000 rows returned).

If we store the count elsewhere we still need a way to ensure consistency.  Right now the reason that  count check is there is because the Redis cache can go out-of-sync with the db state.

Timing things is difficult rightn ow due to heavy load by the mongo->postgres migration script.  Things should improve when the migration is done.

Rows:
matches: ~82 million
player_matches: ~820 million (approximately 10 players per match)
players: ~3.8 million
player_ratings: ~1 million

**Comment by mhartkorn** [comment]
Did a match ever get deleted? If not it could be done relatively easily, I think. The only change to this value would be done in the `scanner` module and (maybe) in a consistence checker.

I image it like this:
- New match is found by `scanner`
- Open transaction
- Add match to `matches`
- Add each player to `player_matches`
- Increase value of `players.match_count` by `1`
- Close transaction
- Clear/refresh player caches

I also thought about making a new module which continuously recalculates the new match data for each player to take some load away from the scanner, so the calculation could be distributed if necessary.

**Comment by howardchung** [comment]
I suppose transactions are one way to approach the problem.

We should probably wait and see before implementing, though.  count(*) should be fast enough once migration is done.

We talked about doing the fan-out tasks associated with each insert with another thread.  It might be something we have to do if we keep adding more aggregations that need to be updated after each match is played.

Migration will probably take another week or so.

**Comment by howardchung** [comment]
The cache is expected to be valid.  It's only invalid in rare edge cases, so the problem of "bad" streaks leading to extended invalidity shouldn't be a huge issue.  Eventually it will get resolved.

**Comment by howardchung** [comment]
Will reopen if count(*) is unacceptably slow
