### ISSUE TITLE
Match not linked on profile

### ISSUE THREAD

**Issue by LFT** [yasp-dota/yasp#748]
Since the latest update, my latest matches are not linked in my profile (or maybe they take a long time to appear ?)

Profile: http://yasp.co/players/45702347/matches

Matches: http://yasp.co/matches/1931446584/
http://yasp.co/matches/1931689231

The display of matches as of today stop at game 1929270004

**Comment by howardchung** [comment]
This is probably a caching problem.  I'll look at it after work

**Comment by Turmfalke2** [comment]
I can confirm this, I have the same issue with  http://yasp.co/matches/1931838082 not showing up.

**Comment by howardchung** [comment]
I couldn't repro on profile but made a change to cache consistency check..

Can someone visit their profile, then play a match, then check to see if the match is there?

**Comment by LFT** [comment]
I'll try to do that after work.

**Comment by LFT** [comment]
Seems to work just fine now.

**Comment by howardchung** [comment]
Great please reopen if it happens again

**Comment by howardchung** [comment]
I think I tracked down the root cause.

I attempted to build an auxiliary data structure called match.slot_to_id to in order to map player slot to ID.  Since the workflow currently deletes match.players (it deletes anything not in the schema, and players is no longer a column in matches), the parse job doesn't have the account_ids of the players.  However when we try to insert the parsed data, we need the account_ids in order to know what players we need to update caches for.

The problem is that creating the auxiliary data structure does not account for the jobs in queue.  Those jobs fail since they don't have the data structure.  I think we should pass players to the parse job, instead of trying to add a new property to the match.
