### ISSUE TITLE
analysis improvements

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#797]
- [x] lower threshold for offlaners, use eff@10 rather than lh@10
- [ ] Group upgrade items together for usage check
Dagon
Necro
BoT
stick/wand
qb/iron talon
shadow amulet/blade/silveredge
- [x] scale rune target with game (1 rune per 4 minutes of game time)
- [x] remove some columns from grading but keep for analysis (early rosh, profanity, courier feeding)
- [x] fix scoring for couriers fed

There are still false alarms that fire if an item is built instantly (e.g., build a Magic Wand and Magic Stick will show up as a purchase even though it had no chance to be used)

**Comment by Turmfalke2** [comment]
mind if I turn this into some kind feed back for the analysis thread?
The unused active items [], expected 0, was a bit confusing on the first glance. It sounds like I am not expected to use my items.
Also apparently I got an A for "Couriers fed: 1, expected 0" - I don't remember feeding a courier, but there is no way I should get an A for doing so.

**Comment by sunnyhwang** [comment]
Here are some suggestions:

-For runes collected, wards bought, please let it scale with game time. (i.e. 4 runes in a 10 minute game/ 3 wards in a 10 minute game)

-Add some exceptions for active item usage for items that are bought either as a component or items that has an active but is mainly bought due to it's stats (i.e. Shadow amulet for component, Bloodstone for stats)

-Have a better role defining system. For the currently version, it looks like that roles are defined by your lanes and the items you've bought. So if I go mid with SF but buys my own lane ward it will count me as a support which is pretty ridiculous. So another way to determine hero roles can be done by looking at CS count relative to the team total CS as well as items, where CS count has a higher priority. So if in a 50 minute game my support Rubick as 200 CS but my whole team has 2000 CS in total, I can still be count as a support despite 6-slotted. But if it's a 30 minute game, a Rubick has 200 CS and 3 big items where the whole team has 600CS combined, it will be determined as a core instead.

-Change standards based on team composition. For example if it is a solo support with 3 cores + a jungle, the wards bought section and courier upgrade time can be changed due to the poor support having a hard time getting any gold.


That's it for current ideas!

**Comment by Jemsuper** [comment]
I don't think i like being graded compared with some arbitrary set numbers. The items unused is nice but move it to the "items used" section in performance. Some of the other values can be kept but instead of judging you with them, just say them as data.
