### ISSUE TITLE
Records showing redundant numbers & etc

### ISSUE THREAD

**Issue by Derek-Li** [yasp-dota/yasp#806]
On the Records page, it seems that a good amount of values for the 'Games' column is useless and repetitive.

Looking carefully, it seems that the table is split into 2 parts: 
1) Stat, Hero, Record, Set 
2) Stat, Games, Total, Mean

Not sure how you would like to do this, but it feels like it could be broken up into separate tables:

Games, Total, & Mean columns do not seem to be directly associated with the Hero, Record, & Set columns. In this case, I think the Games, Total, & Mean columns should be migrated to another table where more generalized stats are shown (Potentially a toggle button on top of the tables switching between specific hero stats & general stats).

If we do go this route, I think the 1st table could contain Stat, Hero, Record, & Set and the 2nd table with Stat, Total, & Mean (we can most definitely add more relevant fields to each table)

![selection_005](https://cloud.githubusercontent.com/assets/3705478/12100235/b929d96c-b2fb-11e5-8e4f-b72b04532468.png)

**Comment by howardchung** [comment]
Basically, it's max, N, sum, avg for each category, which are common descriptors of a data set.  Sure, we CAN split it into multiple tables but we'll be duplicating the name column at the very least.  I think it's important at least to mention N with the record, since not all the records are based on an equal number of games (newer stats have fewer games to draw from)

**Comment by howardchung** [comment]
Closing for now.  Feel free to reopen if you want to tweak your proposal or have a plan for implementation (you can mess around with layout when you have a devbox running)
