### ISSUE TITLE
Roshan & Aegis

### ISSUE THREAD

**Issue by likered** [yasp-dota/yasp#808]
I thought it would be a good idea if there were some more indicators for Roshan kills and Aegis usage

Under Farm tab:
1) Distribution table: add Roshan column with kills

Under Combat tab:
1) Kill Times: add Roshan kill time

Under Objectives:
1) Objectives: Any way to detect who got the last hit on Roshan and give that person the credit of a Roshan kill? (If yes, then hero summons need to be handled)
______

Aegis

Under Performances tab:
1) Utilization: under "Item Use", add Aegis used/timed out

**Comment by howardchung** [comment]
Farm:
We can add roshans killed, but it will only count if the player actually delivered the last hit (combat log kill).

Combat:
Would not be retroactive since we didn't put roshan kills in the kills_log array previously.  Also would need an image to use for roshan.

Objective: Currently we use chat events (text on left side of screen) to determine objectives.  You'll notice that the game just says "Radiant/Dire has killed Roshan" without reporting who killed it.  We CAN determine it through the combat log if a player delivered the last hit to Roshan, but the problem is that these events aren't coupled and we'd have to guess at the association based on time.

Aegis:
Since Aegis isn't an active item the combat log does not report its use.

**Comment by Derek-Li** [comment]
1) If this is implemented, basically #3 is half-done as well.
3) Is it possible to get a time-frame when "Radiant/Dire has killed Roshan" appears or "<Hero> picked up Aegis of the Immortal!", then get the hero who delivered the last hit to Roshan in that time-frame?

**Comment by howardchung** [comment]
1) is super easy and a good beginner project.  Just go to compute.js where we count up the other kills (towers/heroes/necro units) and add one for roshan (npc_dota_roshan I think but you can just use indexOf("roshan")), then go to the views/match/match_farm.jade view and add a column for Roshan kills.

3) Yes, but messy and possibly computationally expensive.  In runParse.js we iterate over all the event logs produced by the parser.  We would need to track additional state of chat event rosh kills and combat log rosh kills, then at the end try to associate them, then modify the objectives array.  Not a clean solution, maybe someone can come up with something better.

**Comment by Derek-Li** [comment]
I will work on it as soon as possible. I'll need to set up my local environment (just built a new pc). Looks pretty straight forward, noticed there will be other things to add (tooltip text, etc)
