### ISSUE TITLE
Various small enhancements

### ISSUE THREAD

**Issue by likered** [yasp-dota/yasp#810]
Specific changes:
* The calculated KDA (ratio?) is shown in the Records page, but not shown anywhere else. Would be nice to show the calculated KDA as a new column in every match (in Overview page).
* Hyphens for Totals section don't seem to be used or does it make sense to have. If the second column of hyphens on the far right are intended, the calculations for the total numbers don't seem to appear. (see below screenshot) 
![selection_008](https://cloud.githubusercontent.com/assets/3705478/12118431/663df99c-b394-11e5-9267-84dcdca300e3.png)
* Under Performances tab, Performances table: hyphens for Radiant & Dire doesn't seem to be used. (see below screenshot)
![selection_009](https://cloud.githubusercontent.com/assets/3705478/12118559/328040c8-b395-11e5-99d2-58ab7cb1d5e9.png)
* Under Profile, Trends tab: list Filters on the side as a column instead of rows. Will increase readability and ease of usage.
* Under Profile, Histogram tab: list Filters on the side as a column instead of rows. Will increase readability and ease of usage.
* Under Profile, Overview tab: add a section under/above Heroes section showing your recently played-with peers (possibly ~1-2 weeks).
* Under Profile, Peers tab: move the Yasp icon for players who use Yasp to a new column to the right of Player Column. This will be more uniform with (see below screenshot)
![selection_012](https://cloud.githubusercontent.com/assets/3705478/12119815/d355ca4e-b39b-11e5-8f8a-16dd235cea54.png)
* Buttons so far away?!?!
![selection_013](https://cloud.githubusercontent.com/assets/3705478/12119923/80fc5c58-b39c-11e5-8cd8-853fca2a8f13.png)

More general changes:
* Allow searches for specific matches, parsed or unparsed at nav bar. Request button could possibly be merged with the match searching OR have a search feature on the right side of the nav bar (IF the Profile button is removed #805)
* Show Hero list
* Show Items list
* On Home page, add a link to the Open Source section to link to github-yasp. Could add links to the other images, but not sure where they could be linked to, maybe for 'In-depth Statistics' could be linked to a page showing sample analysis done on a match & 'Free of Charge' could be linked to the Donation/Carry page (might not be what you want since it's counter-intuitive for a Free of Charge image linking to a Donation page).
* Blog tab could display posts in succession instead of browsing by clicking 'Newer'/'Older' OR have a Table of Contents bar on the left to show previous Blog posts (might be useful for those who want to go back to a specific blog post without having to click 'Older' 5-15 times)

Less relevant:

* Under Purchases tab, Build Times table, player's name seems to be multi-lined. Intended or should it be changed so that player's name shows up on one line? Rest of the Hero columns seem to have the player's name on one line
* Under Graphs tab, we COULD add a graph of every kill made in the match. It will most likely be a repeat of the Kill times table in Combat tab, but it [probably] feels nice to have a graph to see kills at.
* Allow ability to close the "Happy 2016! Reach your resolution to improve your Dota skills with our new analysis feature!" message. Possibly adding an 'x' to the `<div role="alert" class="alert alert-success text-center">Happy 2016! Reach your resolution to improve your Dota skills with our new <a href="https://yasp.co/blog" class="alert-link">analysis feature</a>!</div>`

Ultra un-relevant:
* Do we have some IRC channel or a chat-site (other than Reddit) where players can ask questions or just hang out with other yasp-ers? (more of a personal request)

**Comment by howardchung** [comment]
- [ ] KDA could add to match overview pretty easily.  A good beginner project if you're interested in contributing (IIRC the property is just player.kda)

* Hyphens in Totals section mean the source data is non-numeric.  In this case the data is items, which cannot be summed.  Same with the Lane data in the Performance table.

* Moving filters.  The reason it is the way it is now is to simplify the layout code (same code can be reused for all player pages).  If we need to customize how the query form is displayed for each tab, that adds complexity.  We'd probably consider a PR that improves it if the UX is significantly improved.

* Recent peers.  Technically possible, but I don't really have a clean way of implementing it.  If you just want to see last few weeks/months, apply a filter.  If the intention was to list peers on the overview, it could be added back (although real estate on that page is pretty limited, which is why I removed it).

* Not sure what you mean by moving the little icon.  Isn't it already to the right of the player column?

- [ ] Query form buttons.  Willing to accept a PR that moves the buttons closer together.

- [ ] Search bar.  Probably open a new issue for this if you want to push for it.  I think it wouldn't be too hard to integrate with request.  Basically, check DB for the supplied match_id, if exists, jump to the match URL, if not, redirect to match request page with the ID filled in.

* Hero/Item list--not sure what you mean by this

- [ ] link to GitHub on index page "Open Source" section.  Easy to add, if you want to submit a PR

- [ ] Blog improvements.  Willing to accept PRs, but not a high priority since the blog isn't an critical part of the site.  Each post has a permalink based on its ID if you want to jump to a post by number.

* Multi-line names.  There's no code specifically doing this.  Link a match page with this problem?  It's probably just due to a long name.

* Kills graph.  The rest of the data on the page is sampled every minute.  We COULD add a new graph showing number of kills every minute (extracted from entity) but I am not sure it's worth the extra storage cost.

- [ ] Closing banner message.  Ask @albertcui about this.  It would require saving the close to cookie.  Maybe could be implemented via JavaScript purely-client side (check cookie and hide banner if user closed it previously)

* Chat.  We have a Gitter linked on the repo home page (in the README) but it is not very heavily used.  We could maybe set up Discord or something.  @albertcui ?

**Comment by likered** [comment]
1) Yeah I can work on the KDA
2) Oh I see
3) Makes sense, not a big issue
4) This YASP icon:  
![selection_014](https://cloud.githubusercontent.com/assets/3705478/12127515/a01fa896-b3c5-11e5-8712-ba7bce3663bb.png)
5) I can work on this as well
6) Got this idea after one of the issues created, getting a match id wouldn't be too useful unless you can search for it. Guess we'll see in a bit.
7) General informatio, list of DotA2 heroes & items. I guess it would be more of an encyclopedia showing information, not sure if you want to head this way since it's not really 'analysis', but I think it can open doors to other possibilities. 
8) I can work on this
9) I can work on this 
10) The multi-lined name happened because of the width restriction of the parent div, I'm guessing. 
![selection_015](https://cloud.githubusercontent.com/assets/3705478/12127739/ec0f4a6c-b3c6-11e5-9858-1b9bb92d4bcc.png)
11) Yeah, not worth the extra cost. Just a suggestion, no big gains from this.
12) Yup, pretty much how I would do it as well: when the banner is closed, either set a cookie or a sessionStorage object, implement some logic to display or not, bam
13) For this, I was thinking along the lines of a more open-ended chat. For Gitter, users would need to have a Github account (which causes some inconveniences for those who don't actually code). Discord doesn't look bad, but it still requires a sign-in. IRC would be a good choice if we implement it through the mibbit web client. 
![selection_016](https://cloud.githubusercontent.com/assets/3705478/12127985/71a78314-b3c8-11e5-84bd-a94827c426d3.png)

**Comment by schadowfox** [comment]
+1 for [#yasp@synirc.net](http://widget.mibbit.com/?settings=d46499e28e061590cfb0ed4e29c3ebbb&server=EU.synirc.net%3A%2B7001&channel=%23yasp)

**Comment by howardchung** [comment]
Sure, if you guys want to set up IRC go ahead.

**Comment by howardchung** [comment]
Don't think there were any specific action items here.  please open new issues for specific objectives.
