### ISSUE TITLE
Analysis Flying courier time when 2 flying

### ISSUE THREAD

**Issue by WTFKr0** [yasp-dota/yasp#813]
Hello,

I got a match where my supp buy another flying cour at late game.
In analysis the time of flying is the sum of the 2 times he purchase

Why when he buys same item multiple times, the purchase_time hash is the sum ?

https://github.com/yasp-dota/yasp/blob/master/compute.js#L192

Match example (Oracle) : https://yasp.co/matches/2057450361/analysis
He bougth @ 237 and @ 2682
The time calculated is 2919

Thanx

**Comment by likered** [comment]
Courier #1: 3:57
Courier #2: 44:42

Calculated time seems to be `2739`

Should `time` be passed as a string instead of an int? Think `27:39` would be clearer

**Comment by WTFKr0** [comment]
No times are in secondes here, and 2739 is just 2919 - 180 (3 min flying cour available)

**Comment by likered** [comment]
Getting a bit off topic here, but I was just saying that after the calculations are done. It could be converted into a proper time and shown.

**Comment by howardchung** [comment]
Yeah, the purchase_time hash is the sum of the purchase times.  I did this to avoid having to iterate through the item log.  You can submit a patch if you like to fix it.  It should be relatively rare that two flying couriers are bought by a support.  Generally a second courier buy in the lategame is done by the carry once seven-slotted.

Re: formatting, feel free to submit a PR that formats the time.

**Comment by coreymaher** [comment]
How about something like this: https://github.com/coreymaher/yasp/commit/7b0c8c423156509f4a37ffb2cf3a34c8d59b090a

I've updated the purchase time logic in compute.js to store the first purchase time for flying couriers when at least 2 are bought. I could make it generic and store the first purchase time for all items, but I figured we would want to save space.

It also looks like the purchase log is available in the late_courier analysis check, so maybe it would be best to go through the log there instead of using precomputed purchase_time. Let me know what you guys think.

Also, do you guys have an example replay where a single player buys two flying couriers that I can test with? If not I can try making my own in a bot match.

**Comment by howardchung** [comment]
You can store first time for all items.  No space is used unless we save it to Cassandra for player page aggregations (requires schema change).  Otherwise compute.js is invoked on-the-fly when a match page is loaded.

First purchase is probably more efficient than going through the log.

People linked a couple of replays in the thread but they are probably out of retention by now.
