### ISSUE TITLE
MMR prediction/estimation

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#839]
@nickhh, the machine learning man, will try to see how accurate skill bracket is at predicting MMR :)

**Comment by Juoko** [comment]
Could you maybe elaborate on what you mean by "skill bracket predicting MMR"? From my understanding, the skill bracket labels are designated to defined MMR brackets, so I'm not sure what nick could be investigating.

**Comment by howardchung** [comment]
We can try to estimate a player's MMR based on the skill level of the games they play

**Comment by rossengeorgiev** [comment]
Why skill bracket? You can observe a player's recent matches,and infer their MMR from the MMR of other players in those matches. The only hurdle would be stacks, since their MMR can vary substantially.

**Comment by howardchung** [comment]
We only have MMR for about 840k players (out of about 12 million monthly players), but we have skill data for almost 90% of matches.

**Comment by rossengeorgiev** [comment]
It could be enough. If you observe enough matches for a player, and have at least one players with their MMR being public you could guess their MMR with reasonable accuracy. There are 10 players in a match, you need just one with public MMR to have a data point for the other 9. On top of that, not all 12mil players play ranked. Ranked matches make up between 35-40% of all matches: http://dota.rgp.io/#chart-lobby-type

**Comment by howardchung** [comment]
Interesting.  However we need to consider the computational cost of this.

With the machine learning approach we can just feed the model a bunch of existing data and then give it a player with x,y,z matches in each skill bracket and get back a result.

I guess the most efficient way to do the MMR matching would be to:
* Get all of a player's matches
* Get all of the players in those matches
* Join those rows with (current?) MMR (MMR at the time of the match would also be possible but probably expensive)
* Take the mean of the MMRs in those rows?

**Comment by rossengeorgiev** [comment]
A very crude implementations would be:

* get recent ranked matches for a player without MMR, up to 1-2 days old
* join on players with known MMR (excluding player), but include matches without
* calculate mean MMR for each match
* calculate MMR for the player, if there are X number of matches with mean MMR
* estimate confidence by `((wins - losses) * 25) / 2`. Count all the matches from the query

There are many problems with this approach, and it doesn't consider player being in a party.
Still could be nice experiment.

**Comment by howardchung** [comment]
I'll probably play with this one next.

**Comment by howardchung** [comment]
Implemented.  @albertcui should review it for UI and we should figure out when we want to ship it/light it up/blog post?

**Comment by dbonadiman** [comment]
I would suggest to evaluate the accuracy of this model. So that you can make incremental improvements.
It is possible to do that offline.

(i) Get players with MMR that have played a ranked match in the last days (The same time window you use for the estimation)
(ii) Estimate their MMR 
(iii) Compare the estimated MMR with the one retrieved from the dataset .  (Mean squared error should fit)

Your objective should be to minimize this value. You can use some kind of regressor or simply play with different formulae Average, weighted average, higher time window. 

In this way you are going to minimize the difference between your prediction and the actual MMR.

My guess is that, what you have now it is only an feature for a more accurate model. 
In a general prospective i would suggest an offline regressor model that uses as features something like:
(i) Neighbour MMR
(ii) Avg Last Hit By user
(iii) Avg Last Hit By Neighbour
(iv) Any kind of features that can be representative of the skill (A simple correlation will be enough)

**Comment by LFT** [comment]
It seems to be slightly off from what I've seen. At least for players playing a lot of games in a stack.

I've some friend with a higher mmr estimate than mine, when I believe they're in a lower skill bracket. My latest (20) games (solo and in stack) are all in vh, whereas their latest games (mostly in stack) oscillate between normal/high/very high.

My profile: https://yasp.co/players/45702347 (mmr estimate 3868)
Their profiles: https://yasp.co/players/80106035/ (mmr estimate 3938) ,  https://yasp.co/players/33613511  (mmr estimate 3921) and https://yasp.co/players/43889335 (mmr estimate 3909) .
If it helps, one game with the 3 them stacked (rated high) : https://yasp.co/matches/2215542624 .
I sometimes stack with other friends that are a little below in terms of skill bracket, this might influence the calculated result?

**Comment by howardchung** [comment]
Yes, right now it is a very simple estimate.  Partly this was for performance purposes (since getting a lot of matches for each player is slow).
