### ISSUE TITLE
Ring of aquilla usage + Phantom Lancer

### ISSUE THREAD

**Issue by Jemsuper** [yasp-dota/yasp#865]
It seems that when you get a ring of aquilla on Pl it gets way too many uses

https://yasp.co/matches/2123913789/performances
https://yasp.co/matches/2135221260/performances

**Comment by howardchung** [comment]
Yeah, I've seen this before.  I'm not sure why it happens and I don't have a fix for it.  It seems to happen on illusion heroes, so maybe it has to do with the spawned illusion "counting' as a use.

**Comment by Vali19n** [comment]
Maybe you can fix this bug by checking for the aura status change(on/off).

**Comment by howardchung** [comment]
I think modifier applied/removed triggers whenever a  unit moves in/out of
range

**Comment by Vali19n** [comment]
https://github.com/yasp-dota/yasp/blob/master/java_parser/src/main/java/yasp/Main.java
The onEntityEntered function checks for wards only. Correct me if I'm wrong.

**Comment by howardchung** [comment]
Yeah but that's entities.  Modifiers are from the combat log.

**Comment by ThePianoDentist** [comment]
No idea what the bug is.

But was interested, either this is already fixed or it does not occur 100% of the time.

e.g. normal usage pl with aquila
https://yasp.co/matches/25bc0bafd654550f4837dd43b11b27c5/performances

(in case not fixed only patterns can see so far is that aquila was in 1st item position in yasp when bugged for pl. as well as possibly aquila being replaced by heart later in game and heart being in slot 1 later on. not 100% sure though. replays no longer available

Will try and find some more examples to help pinpoint when exactly occurs)

**Comment by howardchung** [comment]
I don't think this is actionable (i.e., there's no bug on our side).
