### ISSUE TITLE
zero downtime deployment

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#876]
Currently we remove and recreate the Docker container, which results in a few seconds of downtime.

If we use something like https://github.com/jwilder/nginx-proxy to reverse proxy in traffic from port 80 to our containers, we can start a new container with new code, then stop the container with the old code.

**Comment by mhartkorn** [comment]
[HAProxy](http://www.haproxy.org/) might suit you better than nginx-proxy.

**Comment by howardchung** [comment]
I'm looking for something that runs in a container itself and can automatically set itself up withot us needing to edit config every time.

**Comment by mhartkorn** [comment]
I understand, I just wanted to point out an alternative because HAProxy can do out-of-band health checks while nginx (at least in the free version) just can do in-band health checks. That means that nginx will load for a while until [fail_timeout](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server) is reached and then switch to another backend server. I don't know nginx good enough but I think that nginx waits for a HTTP response and because yasp is currently taking its time until it sends data, it could be a problem that nginx is removing healthy servers from the cluster, especially in high-load situations.

**Comment by howardchung** [comment]
done, i think.  20 minutes of downtime
