### ISSUE TITLE
[LSI] all modifying queries failing on postgres due to transaction ID wraparound

### ISSUE THREAD

**Issue by leovn85** [yasp-dota/yasp#883]
This issue occurs today after I reinstall my windows.

After I reinstall the windows, I went to YASP, then logged in but the page with sad tide hunter appears (500 - Woops! Looks like someone fed.). There is no small window appears to input the security code and verify as usual at the steam page.

Here is my profile link: https://yasp.co/players/202652468

**Comment by howardchung** [comment]
We have an active incident right now with all queries modifying the database failing.

This affects login, donations, match insertion, and match parsing (basically everything).

We know the cause: (transaction ID wraparound caused by autovacuum not completing quickly enough), and have a couple of mitigations ready.

* Autovacuum as well as a manual vacuum are running right now.
* It's possible that they will fail due to the same transaction ID issue.
* If that happens, we will need to either:
  * stop the DB, run it in single-user mode and do the vacuum.  Site will be down during the vacuum.
  * Dump and restore the DB. (pg_dump can be done with the DB staying up, essentially read-only mode.  Restore would require us to take the site down for its duration).

**Comment by howardchung** [comment]
Was able to clone the disk and complete a vac on the clone.  I'm going to try swapping the disks.
