### ISSUE TITLE
Make banner message dismissable

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#887]
Probably implement via a cookie that hides it if the user has client-side indicated they want it gone?

**Comment by albertcui** [comment]
The question is how do we clear it if we add a new banner message? I guess timestamp banner messages?

**Comment by howardchung** [comment]
maybe give the cookie a unique name?

**Comment by likered** [comment]
A unique name + an expiration date for the cookie would probably be a great way of doing this.

Making the cookie expire in a few months (or a reasonable time frame) prevents clogging up the user's browser with cookies.

**Comment by coreymaher** [comment]
Cookies are sent with every request. Since you don't actually need that data on the server side, you might want to use local storage instead. I'm not sure what browsers you are targeting, but it's available in browsers that are reasonably new.
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by howardchung** [comment]
Continued in https://github.com/yasp-dota/ui/issues/14
