### ISSUE TITLE
Matches list

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#893]
I think you should do these changes:
- make the color of the match id red/green instead of showing the result of the match as a letter;
- combine the KDA bars like in the stats menu of the game, but keep them horizontal;
- showing if the hero was random or not could be a nice detail. You could add it to the game mode column as a simbol near the game mode name or under it as "(random)".
- The name of the "As" column in the most played heroes list is not very intuitive, so try to change it to something else.
- You could make a settings menu to customize the stats and add these to it, if you don't think they should be set as default.

Bug:
- the mmr is not correctly shown. On my profile it shows around 200 less mmr for solo and around 100 less for party.

Potential bug:
- the mmr on other profiles is shown as "N/A". I only found a profile with mmr listed after I checked 7-8 profiles. I don't know if it's a bug, they've set it as private or they didn't play ranked.

**Comment by howardchung** [comment]
* Color change, could do.
* Combining KDA bars--not sure exactly what you mean.  I'd prefer to keep the columns separate so it can sorted on.
* Random: We don't have this data from the API.  It might be possible from replay parsing but would need investigation.
* As column--any suggestions for alternate wording?
* Settings menu--generally I try to avoid storing too much per-user state.  It also adds complexity as there  is more user input to validate and save.

* MMR--usually it can be delayed a few games.  There isn't much we can do about it since Valve doesn't update the profile cards immediately.

* Missing MMR.  They probably just don't play ranked or haven't shared MMR.

**Comment by Vali19n** [comment]
- Random: you can check the starting gold, but it will have some edge cases like when the player is afk and picks random after a long time
- Column: played, matches, times

**Comment by howardchung** [comment]
Did the colors and the text change:
http://colab-sbx-244.oit.duke.edu:5000/players/88367253

**Comment by howardchung** [comment]
I don't know if we should explicitly put the W/L somewhere.  Color-blind users may have difficulty otherwise.

**Comment by Vali19n** [comment]
I think you're right about the W/L thing.
