### ISSUE TITLE
Numbering on trends

### ISSUE THREAD

**Issue by Vali19n** [yasp-dota/yasp#915]
In the Trends tab, match count starts at 0. You should change it to 1, because most people aren't programmers.
EDIT: You can either do this by showing i+1 or by ignoring the 0 index in arrays. I think the later is more cpu efficient, but will interfere with the development because you must remember to start from 1.

**Comment by howardchung** [comment]
@albertcui should we do this?

**Comment by Vali19n** [comment]
you can either do this by showing i+1 or by ignoring the 0 index in arrays. I think the later is more cpu efficient, but will interfere with the development because you must remember to start from 1.

**Comment by likered** [comment]
Wouldn't it start from 0 though? If you're new and you joined Yasp without playing your first game, you would start from 0 matches with no stats.

**Comment by Vali19n** [comment]
I know that, but the problem is that the graph shows stats at position 0. https://yasp.co/players/257861991/trends

**Comment by likered** [comment]
Ah I see, so it's 0 to length-1

ok

**Comment by howardchung** [comment]
I'm going to keep it at 0 for consistency with the loop variable.  I don't think it really bothers anyone.  Actually we used to have a more detailed tooltip showing the match ID, hero played, and value per match (more useful than just an index).  We got rid of it because it took a lot of space when we did the Redis caching, but with Cassandra we assemble it on the fly so it's not as much of a problem.

Could consider bringing that back if people want it.
