### ISSUE TITLE
Dynamic Ads

### ISSUE THREAD

**Issue by albertcui** [yasp-dota/yasp#917]
Production [yasp.co](yasp.co) is looking to be going into the red after this month.

One solution is to bring back ads. Ideally we shut them down when the monthly cheese goal is met. This would hopefully encourage donations.

Idea curtesy of @angelasun55.

**Comment by likered** [comment]
Suggestions:

1) Displaying video ads with a time-interval on the side of the pages (once every 5-10 minutes?). This would be video based, I guess. It can show a video for ~1-2 minutes and disappear after it's completed.
2) Parsing matches displays video ads until match is finished parsing.
3) Create a new tab `Support` or something. Volunteers can watch videos ads on that page to gain some secondary virtual currency (maybe like Mangos or something) that can be used to redeem some arbitrary goods/services of some sort. (making it fun for people who want to help keep the site alive)

**Comment by howardchung** [comment]
I think we want to keep it minimal and just display some basic banner ads.

@albertcui would you make it dynamic like how the "behind" is triggered, or is it simply a monthly reset thing (always start off displaying ads and shut them off when goal is met for rest of month)

**Comment by albertcui** [comment]
Would probably start them on then turn off when goal is met every month.

**Comment by howardchung** [comment]
Okay.  This is like a <5 line change so I dunno when you want to implement it.

**Comment by mhartkorn** [comment]
Have you thought about instead of using GCE to use a single very large dedicated machine? I looked at your [GCE invoice](https://imgur.com/a/dLZMg) and as far as I can see, you are using a redis server (highmem 8 VCPU) for ~$350, a frontend webserver (highcpu 2 VCPU) for ~$200, and a persistent storage for the DB for ~$400. I don't know where the DB server is running, though.

If I look around for dedicated server hosting, I can find (in Germany, with 19% tax included) servers with 128 GB memory, 3 TB SSD, and 100 TB included traffic for about $400, which is less than half the cost of GCE for March. Maybe you can throw in a small dedicated static content server for the assets and such. It's not as fail-safe but given that YASP is a private project, it should be known that the site may be down once in a while. There should be similar servers in the US, I don't know the providers there and it should be significantly cheaper because of the lower tax rates in the US.

Correct me if I am talking bullshit here, please. I hope, I didn't read the invoice wrong.

Link to the server I was talking about: https://www.hetzner.de/us/hosting/produkte_rootserver/dx291

**Comment by howardchung** [comment]
Actually we changed things up a little bit this weekend:

Old:
hm-8 for Redis, Postgres, Cassandra, backend and frontend ($256)

New:
hm-8 for Redis, Postgres, Cassandra ($256)
preemptible standard-1 for backend ($10)
preemptible g1-small (minimum 3) for frontend, sitting behind load balancer.  Should scale dynamically with load if we get a traffic spike. ($21 + $20 for load balancer)

The same:
preemptible highcpu-2 for parsing (~10 instances running usually) ($200)
3TB of SSD storage ($510)

The idea is that we rarely need to update our DB software and it now gets to run on its own dedicated reliable instance.  

We have 3 web instances rather than running them all on a single one so we can rolling-update with new code without downtime.  The backend services don't need 100% uptime so they are in their own preemptible instance and can be updated just by recreating the instance (it will pull latest image from Docker).

Yeah, GCE is going to be more expensive than a dedicated hardware provider like Hetzner, but:
* Exporting out of GCE is going to very expensive and pretty disruptive to service
* GCE has great tools to make scaling and monitoring easy
* Backup is easy since we can take snapshots anytime and disks are automatically replicated

**Comment by albertcui** [comment]
Yes the biggest reason is scalability. We can essentially infinitely scale
disks and instances to deal with traffic and user spikes.

**Comment by mhartkorn** [comment]
> Actually we changed things up a little bit this weekend:

Oh okay, good to hear. Do you have statistics about how often YASP has cache hits vs misses, CPU/momory usage of all components? I saw a "bug" report about this here once but I don't know how far it got solved. If you could publish the results somewhere publicly everybody could look for bottlenecks and improvements.

For a short term solution to make people donate more, you could rework the cheese model a bit. To parse all match data, the user has to visit once in 3 days or can pay 1/month per cheese (for all new cheese buyers of course)? And heavy users with a lot of games (e.g. >2000) get a personalized, prominently placed message every 100 games that donating would be much appreciated until the user closes it or donates cheese.

**Comment by howardchung** [comment]
Caching is a complicated question to answer.  There are multiple levels of caching involved, from the web level (Cloudflare) to internal caching (Redis + Cassandra).

3 days timeout seems pretty short to me.  I think we went from 3 days to 7 days to 14 days, which is where we're at now.  We might consider going back to 7 if we need some more cost-cutting.

**Comment by howardchung** [comment]
thanks to donations we should be good until at least may.  Moving this

**Comment by howardchung** [comment]
@albertcui implemented.  Can turn on feature switch whenever
