### ISSUE TITLE
postgres 4b toast limit

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#935]
We aren't hitting this limit yet but it's something we need to keep in mind:

Postgres only allows a table to TOAST 4 billion rows (and will suffer performance degradation on inserts prior to that).

We currently have over 500 million TOASTed rows (each player_match in a parsed game generates about 10).  This is in approximately 14 months of operation, but we're likely to parse at a faster and faster clip.  Currently we're doing just under 60k a day, so we're eating OIDs at a clip of 180 million a month.  We may start running into issues in another year or so.

Perhaps @gortiz has some ideas on solutions for this problem.

Solutions:
* Partition the table.  Time-consuming and messy, but the TOAST limit applies per table so this would work around it.
* Move match data out of Postgres and into Cassandra (also time consuming and messy).

TODO
- [x] config change ENABLE_CASSANDRA_MATCH_STORE_READ
- [x] turn off ENABLE_POSTGRES_MATCH_STORE_WRITE, deploy backend
- [x] snapshot disk-postgres
- [x] create disk-postgres2 (100gb ssd?)
- [x] attach disk-postgres2 to core-1, mount to /var/lib/postgres/data2
- [x] `drop table matches;`
- [x] `drop table player_matches;`
- [x] `docker stop postgres`
- [x] `rsync -avP /var/lib/postgresql/data/pgdata /var/lib/postgresql/data2/pgdata`
- [x] unmount disk-postgres
- [x] unmount disk-postgres-2

**Comment by gortiz** [comment]
At 8kdata we like to use table partitions when we detect very big tables.
In this case, it seems to be an optimal case, as you can split data by the
date it is inserted.

The idea is to use a parent table
<http://www.postgresql.org/docs/current/static/ddl-inherit.html> and as
many child tables as you need (you can even create one table per month or
something like that). A select sentence on the parent table will return all
child table rows... but it gets better: If you can create check constrain
on each table (like a date interval) and then you query the parent table
with a where condition on the same attribute (like select * from
parent_table where date > x), then only the children tables that fulfill
the condition will be scanned.

The two main cons of that approach are:

   - The restrictions inheritance introduce (no fk, no unique indexes,
   etc). I don't remember the schema that YASP is using, so I don't know if
   this applies.
   - Child tables must be created manually and the modification sentences
   must run agains the child table. We usually use stored procedures abstract
   the table management from the business logic.

I will talk with my colleges to look for more solutions or easier ways to
implement the parent-child partition.

2016-03-23 9:11 GMT+01:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
Here's the schema:
https://github.com/yasp-dota/yasp/blob/master/sql/create_tables.sql

The thing is that we don't really do date queries.  The primary queries are for:
* individual matches (select 1 row from matches and 10 rows from player_matches)
* players (select a few thousand rows from player_matches joined with matches)

Players however will have matches from across a huge time range (years), so we'd have to look in multiple child tables.

Keys:
player_matches have a match_id that reference matches.  However we don't rely on the key being there.  We don't do operations like delete matches that would benefit from deleting all associated player_matches.

**Comment by ahachete** [comment]
Hi, a @gortiz colleague here.

I agree partitioning is a way to go. Regardless of TOAST, big tables behave badly anyways, here and in any other database. I'm sure there's a natural concept for partitioning, that could be expressed, and would benefit queries, but I cannot know without a more detailed understanding of the data model.

Independently of this, looking at the DDL, I have several questions:

- Why so many json fields? The idea of having json is to have fewer of them. This could be multiplying the number of TOASTed entries. What data is in them?

- TOAST will only toast (by default) compressed values that are over 2KB. Is this really your case, are *all* those jsons that big?

- Why use json[]? That's... unusual. json supports itself arrays (containers).

- Why not jsonb instead of json? It has many benefits and few drawbacks (whitespaces are not preserved).

I believe partitioning and a clever redesign of the schema would solve this problem right away.

**Comment by howardchung** [comment]
The json fields are based on the event types we get from the match parser.  In general we group all of the log entries of a single type into a single json object.  Having more fields also lets us choose the columns we want to project more granularly.

No, not every field is big.  It looks like something like 10 of them are being toasted, out of 35 or so.

Json[]:  There was some weirdness with the nodejs driver not working sell with json arrays stored in json columns.

Jsonb: we don't query on the json internals.  We just need to read the data back out.  Jsonb uses additional disk space so we wanted to save storage space.

**Comment by teoincontatto** [comment]
Hi, as @gortiz said we used partitioning in postgres before. We have to create some utility functions to manage partition creation. Those functions do the job of creating child tables with proper checks, indexing or tablespace tuning. Also, since the data in partitions are stored in child tables, the utility functions allow to retrieve the name of the table on which you have to insert, update or delete based on the fields used to partition. These are some extensions that would help in doing most of this work:

https://github.com/keithf4/pg_partman
https://github.com/moat/range_partitioning
https://github.com/postgrespro/pg_pathman (pg >= 9.5)

**Comment by ahachete** [comment]
I understand what you say, @howardchung However, that large number of json fields is what is probably causing a lot of TOASTED columns. If you would somehow group them, you will end up with fewer, even if larger, json fields, significantly diminishing the problem. That's, indeed, the purpose of json: have arbitrary data, that is not "static", grouped together.

Regarding jsonb: if you are not querying the data, is it immutable too? If this is the case, why don't you use https://github.com/citusdata/cstore_fdw? It provides amazing results (and won't be subject to TOAST).

json[] is still really weird to me, I'd fix that ;)

If you would ask me, I'd conduct a schema redesign. Of course I'm biased, we do this professionally ;P but even though migration could be painful, many storage, performance and programming benefits may be obtained.

Let us know how you finally fix the TOAST issue! As @teoincontatto also suggested, using pg_partman (pg_pathman looks impressive, but it's still beta and only 9.5) would be a great idea.

**Comment by howardchung** [comment]
I'll see about doing the following:

* matches.url: We don't need this forever, so we can store it temporarily (as a replay salt integer) in Redis.
* parsed data fields to a single jsonb blob in its own table parsed_player_matches (primary keys match_id and player_slot, same as player_matches)

**Comment by ahachete** [comment]
OK, good luck! Let us know if you need more help / opinions :)

**Comment by howardchung** [comment]
Testing migration to Cassandra now for match data.
