### ISSUE TITLE
Problems with MMR estimate

### ISSUE THREAD

**Issue by rossengeorgiev** [yasp-dota/yasp#943]
As it currently stands the estimate is merely the mean of the Solo MMR of players in the last 10 matches. That can produce widely inaccurate results in certain conditions.

1. Ideal conditions
 1. last 10 matches are all ranked and no parties are involved, some players show MMR
2. Problematic conditions
 1. no players showing solo MMR
 2. matches containing parties
 3. player himself plays in a party/parties
 4. last 10 matches are not in ranked
 5. player has not played for a while

I assume `2.i` is currently solved by displaying some sort of error message?

It's impossible to address `2.ii` and `2.iii`, only guess at best.

`4.iv` and `4.v` can be easily  resolved by adding more conditions to the SQL query:
https://github.com/yasp-dota/yasp/blob/ccb123f6d18190ee3674634e5dcd3176b9dc5dbc/routes/api.js#L67-L69

Only `lobby_type = 7` and a time constrain on `start_time`. Perhaps, no older than a week? An alternative approach would be to estimate the match average MMR for every ranked match as they finish and record the result. That would remove the need for a time constrain. No result would fallback to the same error message as `2.i`

Finally, I propose replacing the estimate with a 95% confidence interval, instead of the mean. Then it will be immediately obvious when the estimate is inaccurate. That would to some extend remedy `2.ii` and `2.iii`. 

```
{
"min95CI": mean - 2 * stddev,
"max95CI": mean + 2 * stddev,
}
```

**Comment by howardchung** [comment]
Yeah we display N/A when mean is 0.

The problem is that if we filter only ranked matches then it won't work for players who don't play ranked.  While obviously not as accurate it's better than nothing for players who want to use the tool for estimation.

I don't know if there's value in a time filter.  If you don't play for a week then your rating hasn't changed, unless we add a decay.

I agree we could provide more context/confidence on the estimate, such as stddev and n (number of data points)

**Comment by rossengeorgiev** [comment]
> The problem is that if we filter only ranked matches then it won't work for players who don't play ranked. While obviously not as accurate it's better than nothing for players who want to use the tool for estimation.

I understand, but you might as well just `random` a value at that point. I play ranked exclusively, and my unranked MMR is probably at least 1500 away from my ranked. There is no way to determine the distance between the two. In my opinion it's better to show N/A.

> I don't know if there's value in a time filter. If you don't play for a week then your rating hasn't changed, unless we add a decay.

Absolutely. However the rating of the players that you are inferring from could have changed. Are you caching the estimate, until the player has played more matches?

I think confidence interval is nice and simple as it doesn't require people to know statistics. 95% chance that their rating is between the two values. Intuitively when the two values are closer its more accurate. If you hit parties, you'll get wider result, but the estimate won't be completely wrong.

**Comment by howardchung** [comment]
We're computing the estimate based on the current MMR of the players involved.  So yes you're right that it's possible for the estimate to shift without even playing at all.  If a player hasn't played for months it's possible for the estimate to drift due to other players moving up or down.  

Potential problem with stddev: What if there is only one player in the matches with MMR?  Then the stddev will be 0 and we appear to be highly confident, but it's actually because our data is limited.

**Comment by rossengeorgiev** [comment]
Yeah, we will need more than one player. From my statistics I gather that 1 in 5 players shows MMR. Thus `0.8 ** 10 = 0.1` probability that for given match none of the players show solo MMR. Let's say we only display a result if we have at least 1 player from 3 different matches, out of 10.  Thus, `0.1 ** 8 = 1e-8`. That's a pretty low probability of getting 8 matches without a single player showing MMR. Let's go extreme, and say that only 1 in 10 players shows MMR, then you get about 2% chance to get 8 matches without a single player showing MMR. 3 samples seems fair enough for CI.

**Comment by howardchung** [comment]
A complicating factor is that a player can show up more than once.  So is N here the number of distinct players, or the number of total data points?  Example: If you show MMR yourself you will appear 10 times in your last 10 games, but it's really only one data point.

I think for the stddev formula to apply, we need to use 10.  However we can inform the user of the number of distinct players found as well.

**Comment by howardchung** [comment]
A potential issue:

I think the problem with confidence interval is that it gives a bound to the average of the players in the matches.  If we have a player who does not show MMR, but we find that in their last 10 games, they played with a 5k player 2 times and a 3k player 5 times, we can use the CI to bound the true average of the players in those matches.  However, that doesn't say anything about the average of the specific player we pulled those matches for.

**Comment by howardchung** [comment]
implemented, try it out:
http://colab-sbx-244.oit.duke.edu:5000/players/88367253

**Comment by rossengeorgiev** [comment]
Looks good.

> A complicating factor is that a player can show up more than once. So is N here the number of distinct players, or the number of total data points? Example: If you show MMR yourself you will appear 10 times in your last 10 games, but it's really only one data point.

Using distinct players would be nice, as it would reduce the effect of parties. Say, the player is always playing with that one friend, and then instead of having 10 samples from that friend we get one.

Looking at the diff, I see that `2.iv` and `2.v` remain unresolved.

**Comment by howardchung** [comment]
I think it's best to use last 10.  It will reflect whatever the user has played recently, whether it's ranked or not.
 
As for time range I'm not sure if that is useful.  Users can see how old the matches are and consider the estimate with that knowledge.

**Comment by howardchung** [comment]
I rewrote the code.

* Using Redis now for much faster speeds (to the point we can load it directly instead of having to click a button to trigger an async call)
* Since we are tracking average match MMR now anyway, I am using that for the estimates.  Helps reduce the effect of outliers since each match will (usually) have more than one data point.
* Redis lists hold up to 50 matches of data per player.  Larger sample=more accurate result, maybe?

**Comment by rossengeorgiev** [comment]
This sound really good. 

> Redis lists hold up to 50 matches of data per player. Larger sample=more accurate result, maybe?

50 matches is a lot, I'd go with lower value. 20-25, should be good enough. We don't want too many or too little recent matches, otherwise the spread could be wide.

**Comment by MMREstimate** [comment]
The current MMR estimation is very imprecise. The 95% CI for a player's estimated true mean MMR might be [2800, 5200]. Such wide estimates are not worth much.

I'm looking into ways to greatly improve your estimate. A few questions:

- Howard, you said you are "tracking average match MMR". Does this come from Valve, i.e., are they now publishing the actual average MMR for a given match (perhaps by team), similar to what's shown in the pregame of Ranked Matchmaking?
- Do you have a dataset against which I can test a few methods? The JSON Data Dump on the wiki seems to be match-specific data with no player MMR data. I'd need (1) player MMR data; (2) match data; and (3) player Peers data in order to start testing. I expect I can derive #3 from #2.
- If you don't have a dataset available to download, could you answer a few questions about the shape of the data? For example: How many matches exist in which all 10 players have exposed their Ranked Solo MMR? How many matches exist in which exactly 9 players have exposed their Ranked Solo MMR?

Depending on the data, you may be able to completely determine the Ranked Solo MMR of a good chunk of the player population, after dealing with some obvious problems (heuristically avoiding parties, culling anonymous players, determining Valve's matchmaker accuracy in attempting to balance the two teams' average MMRs).

**Comment by howardchung** [comment]
* Valve does not publish MMR data.  It is data we have collected by checking the profile cards of players (who share it on their profile in-game).

* I don't have a dataset handy.  It is very rare to have a match with 9/10 players sharing MMR.  Typically it's more like 2-4.

**Comment by MMREstimate** [comment]
Okay. Even without Valve publishing average match data, a few approaches seem straightforward. Here's the one I think would work best given what you've said. The implementation is not trivial, but the precision in your results would be high.

**Summary:** Construct a system of equations containing all MMR relational information from matches that fit a certain criteria. Use players' unknown or known MMR values as variables for each match. Solve the system to determine a portion of the population's unknown MMR values. Then estimate the remaining unknown MMR values using a package such as [systemfit](https://cran.r-project.org/web/packages/systemfit/systemfit.pdf).


**Details:**

**Prelim**

- Treat all players' Solo Ranked MMR as variables in the system.
- Use only matches in which no parties exist. (See Problems, below.)
- Assume Valve's matchmaking algorithm only matches teams with equal average MMR. (See Problems, below.)
- Let k be the number of players in a given match with exposed MMR.
- Let p_x represent the Ranked Solo MMR of Player x.

**Constructing the information system**

1. Each player with exposed Ranked Solo MMR adds a new row to the system.

  Example: Player 11 has exposed Ranked Solo MMR of 3500. There are 50000 players. Then add the following row to the system of equations:
`   (0)*p_1 + (0)*p_2 + [...] + (1)*p_11 + (0)*p_12 + [...] + (0)*p_50000 = 3500`

2. Each match for which k < 10 adds a new row to the system.

  Example: A match between players 1, 2, 3, 4, 5 against players 6, 7, 8, 9, 10. There are 50000 players. Then:
`  (1)*p_1 + (1)*p_2 + [...] + (1)*p_5 + (-1)*p_6 + (-1)*p_7 + [...] + (-1)*p_10 + (0)*p_11 + (0)*p_12 + [...] (0)*p_50000 = 0`

Matches for which k = 10 add no new information to the system, as all players' MMRs are exposed. These matches can, however, be used to evaluate Valve's matchmaking accuracy (see Problems, below).

**Solving the system**
After populating all possible rows to the system, solve the system. This will newly determine near-exact MMRs for a portion of the playerbase who do not expose their MMRs.

The remaining unsolved variables and relations in the system contain information. Use another method with these relations to further estimate remaining players' MMRs. For example: Use an estimator package such as [systemfit()](https://cran.r-project.org/web/packages/systemfit/systemfit.pdf) to estimate the remaining players' unknown MMR values. Given a sufficient number of qualifying matches, estimates' standard deviations may be as low as 100 MMR.


**Problems**

_Problem 1._ 
Players' Unranked Solo, Unranked Party, Ranked Solo, and Ranked Party MMR values are all different.

_Mitigation 1._

- Only use Ranked Solo MMR on the first pass.
- Discard matches in which there exists at least one party.
- Heuristics to detect parties might include checking each player and counting the number of Peers that exist for that player. ("Peers" are players with whom the player has played at least 1 match in the past.) If any player has at least 1 Peer, discard that match.
- The problem with this heuristic is that does not discard matches in which two players play Party Ranked together for the first time.

_Problem 2._ 
This approach requires accommodating for players' MMR changes over matches. Player 555 might have 3000 MMR in Match 999, but only 2975 MMR in Match 825.

_Mitigation 2._

- One dumb heuristic: Assume +25/-25 for each ranked win or loss.
```
Example:
Player_555 has exposed MMR 3000 after their most current Match, ID 999.
Before Match_999, Player_555 played in Match_825 and Won. 
    Thus, we assume their MMR was 2975 in Match_825, using p_555 = 2975 in row_825.
Before Match_825, Player_555 played in Match_717 and Lost.
    Thus, we assume their MMR was 3000 in Match_717, using p_555 = 3000 in row_717.
```
- The problem with this heuristic is that matches do not always award +25/-25 points. Finding the actual reward distribution per match to compute a reasonable incremental variance would require a dataset of players' MMR changes over time. Then that variation could be built into the variance on every unknown MMR variable in the system.
- Fringe case: The algorithm must account for players who abandon a match that is Won. Players who abandon a winning match receive -25 points (instead of the usual +25).

_Problem 3._ 
Valve's matchmaking algorithm does not always match teams with equal average MMR.

_Mitigation 3._
Inspecting matches for which k = 10 would give an idea of the magnitude of the variance in Valve's matchmaker. Build this variation into the variance on every unknown MMR variable in the system.

_Problem 4._
Some players are fully anonymous and cannot be uniquely identified in the data. (Is this true?)

_Mitigation 4._
Discard matches in which there exists at least one anonymous player.


**Other considerations**
- A similar approach could be used to compute or estimate players' Ranked Party MMR values by filtering matches differently.
- I doubt Ranked and Unranked MMRs are strongly correlated. I'm not sure how to accurately estimate Unranked Solo MMR or Unranked Party MMR.

**Comment by gortiz** [comment]
>
> *Mitigation 1.*
>
>    - (...)
>    - Heuristics to detect parties might include checking each player and
>    counting the number of Peers that exist for that player. ("Peers" are
>    players with whom the player has played at least 1 match in the past.) If
>    any player has at least 1 Peer, discard that match.
>    - The problem with this heuristic is that does not discard matches in
>    which two players play Party Ranked together for the first time.
>
> There is another problem. It is not uncommon to play more than one match
with the same guy even if he is not in your party, specially on very
low/very high mmr

**Comment by rossengeorgiev** [comment]
@MMREstimate there are a few things preventing any good analysis of the system. In no particular order:

* Roughly half of all dota players, are anonymous, they don't share match data with third party, all of them share the same id number
* Roughly 20% of all players show solo MMR on their profile, probably less
* the API does not indicate presence of a party, how many, which players etc (you can't determine which MMR is used solo or party for a particular player)
* the API does not indicate which players received -MMR after leaving
* for matches at the tails of the distribution there could be large variance in MMR of players

**Comment by MMREstimate** [comment]
@rossengeorgiev This is why I'd requested an MMR dataset in my first post. Thanks for the info.

Comments on your concerns, in order:

- If 50% of players are anonymous, that still means 1 in ~1000 matches have no anonymous players. With match numbers in the trillions, you have a ton of information. It's not obvious to me that this is a deal-breaker. (Also: Is it really that low? Looking at a few dozen of my own recent solo ranked games, I see ~25% of my matches having no anonymous players. Perhaps anonymity is clustered by MMR or lobby type, or perhaps my sample is just a fluke.)

- 20% of players showing solo MMR on profiles is not a problem. The majority of the information in the system comes from relational sets, not explicit player MMRs.

- For identifying parties, I offered one heuristic in the "Problems" section of my long post. There are likely other workable guessing methods. I don't know what percentage of matches have zero parties, though, which could stop this approach if it turns out to be very low.

- The API does include information on whether or not a player abandoned a match. This is sufficient to determine players receiving -MMR in Won matches.

- I agree with you that the matchmaking average MMR variation between the two teams will likely be larger on the very-low and very-high MMR tails. Estimates for the best and worst players will have larger error bands.

**Comment by howardchung** [comment]
I might be able to get you the MMR data.  Do you need anything else?  You could get recent live match data from the Steam API.

**Comment by MMREstimate** [comment]
Thanks Howard, getting the data is a prereq for me helping more than just outlining a possible solution. If it's a hassle to get the data or if this is low priority for you all right now, no worries.

No, I don't need anything else. I can download your match datadump from the wiki for testing.

**Comment by howardchung** [comment]
The dump doesn't contain all matches, only the 3.5 million we parsed from
Jan to Dec 2015.

**Comment by howardchung** [comment]
If you want a more representative sample you should pull fresh data
directly from the Steam API.

**Comment by howardchung** [comment]
[mmr.zip](https://github.com/yasp-dota/yasp/files/230996/mmr.zip)

Here you go.  You'll need to do some parsing (simple regex should do).  Format is account_id, solo MMR on the line immediately after.

**Comment by MMREstimate** [comment]
Perfect. Yes, this is trivial to parse. I'll start poking around this weekend and see if I can help you out.
