### ISSUE TITLE
Advanced Picks Filtering

### ISSUE THREAD

**Issue by xmindfirex** [yasp-dota/yasp#964]
A feature that would allow you to fill in any number of players on either team - then filter to see all combinations of games that met that criteria with # of games and win rates. If these could also be further filtered down into MMR brackets similar to the Meta Heroes Page on Dotabuff. 
The end result could be something like 3-4K, with an invoker, pudge, Sven on one team, what is highest win rate team if you already have a void, OD, and witch doctor. 
I would like to learn how to do this/help out if possible. I have programming background but have done nothing previously with Dota data.

**Comment by howardchung** [comment]
Sure, if you're interested you can take a stab at this.

* Presumably the search would start scanning by match_id in reverse order.  I think we'd have to limit the search though, because it would take hours/days for a query to complete on the entire data set.
* I think you'd start by putting a new endpoint in web.js that executes the query.  After you've tested it then you can build the UI for it.

**Comment by xmindfirex** [comment]
Yes, I would only want to do it on a recent set of matches, perhaps the most recent X weeks. 
How do I get started on running these queries?  I know SQL and have some experience with JavaScript but I am not familiar with how to reach this data or execute the query.

**Comment by xmindfirex** [comment]
Sorry only part of the message was showing I think because I am on a mobile browser. I will look into this tomorrow when I am back at my PC. Thank you.

**Comment by howardchung** [comment]
You're going to need your own data set to develop against.  You can try following the setup instructions in the README, then running `scanner` for a bit in order to gather some match data.  Some people have reported issues with cloud9 so you may want to use your own Ubuntu 14.04 environment.

**Comment by xmindfirex** [comment]
I got set up on cloud 9, and also cloned the repository on my own Ubuntu environment.  I think I need a little more direction on how to actually execute the data pull.  Do I actually gedit the web.js document then execute it to run the query?

**Comment by howardchung** [comment]
You can use any text editor although I recommend something with better
syntax highlighting.  See examples in queries.js for how we interact from
the db within JavaScript code.  You can also run queries directly against
the DB with the psql shell but I suspect you'll need to process the results
with JS anyway.

**Comment by xmindfirex** [comment]
Sorry I have never worked with something quite like this.  For an example, if I wanted to pull a query of just all the Match IDs from the past week, how would I execute that?

**Comment by howardchung** [comment]
You'd need the data first.  You can run the scanner to pick up new live matches from the API.  It can only pick up future matches though.  I imagine you'd run it for a few minutes to pick up a few thousand matches and use that to develop your code.

**Comment by xmindfirex** [comment]
I am getting an error running the scanner.js on Cloud9.  Is this the reported issue you mentioned previously?
Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:5432                                                                                                                                       
error occurred during buildSets: Error: Pool was destroyed

**Comment by howardchung** [comment]
It looks like your postgres isn't running.  Try sudo service postgresql restar

**Comment by howardchung** [comment]
Also you'll need to set ENABLE_INSERT_ALL_MATCHES to 1 in your .env to insert everything.  By default it only adds matches of tracked users, which your dev environment won't have any of

**Comment by xmindfirex** [comment]
on my machine when I enter:
npm run task scanner
I get Error: ENOENT, open 'yasp/node_modules/task/package.json'

**Comment by howardchung** [comment]
Don't forget to also put STEAM_API_KEY in your .env

.env is located in the project root (same place as .env_example).

Run scanner via `npm run dev scanner`.

If you want to run both scanner and web, `npm run dev web,scanner`.

**Comment by xmindfirex** [comment]
I got a similar error with  npm run dev scanner    but it appeared to work with  npm run scanner

1. where are the results going?
2. do I need to / how do I stop the scanner?

**Comment by howardchung** [comment]
`npm run scanner` shouldn't work.  I just tried it locally and it fails with "missing script" since package.json doesn't contain a script called scanner.

The results should be going into your postgres DB.  You can check by opening a psql shell with `npm run psql`, then do something like `select count(*) from matches;`.

To stop the scanner, just ctrl+C its window.

**Comment by xmindfirex** [comment]
what do I put for STEAM_API_KEY in the files?

**Comment by howardchung** [comment]
Get one here:
https://steamcommunity.com/dev/apikey

**Comment by xmindfirex** [comment]
I got my key, i edited the .env_example and added the ENABLE_INSERT_ALL_MATCHES=1 as well.  I then did: cp .env_example .env   
again.  I am still not getting any results.

**Comment by howardchung** [comment]
`cp .env_example .env` overwrites your `.env` with the example.  You'll need to redo your changes

**Comment by xmindfirex** [comment]
yes, I changed the actual example then overwrote it.  I confirmed the .env has the values.

**Comment by xmindfirex** [comment]
well im learning a lot as I mess with this but I have to call it a night for now.  Thanks for your help, I am excited to get this figured out and be able to pull some data from the API

**Comment by xmindfirex** [comment]
i found in my directory I do not have a DEV folder under node_modules.  My scanner.js is directly in the main folder, which is why it seems to run when i just do NPM RUN SCANNER.

**Comment by howardchung** [comment]
Okay.  Post the log traces if you'd like me to help with the scanner issue.

**Comment by howardchung** [comment]
You should not have a dev folder under node_modules.  scanner.js should be in the root, and you should be doing everything from the root.

**Comment by xmindfirex** [comment]
well when i do the command  npm run dev scanner i get the error message: ERROR: ENOENT, open 'yasp/node_modules/dev/package.json'
when I looked up that error message it says its because that directory doesnt exist, which i can confirm (and you agreed it is in the root). So why when I run it does it look for the dev folder under node_modules?

**Comment by howardchung** [comment]
Try clearing your node_modules folder: `rm -rf node_modules` and then do `npm install` again.

What version of node/npm?  `node -v`, `npm -v`

**Comment by xmindfirex** [comment]
I did that process, same error message.  My npm verison is 1.3.10
I did not have node installed - installing that now

**Comment by xmindfirex** [comment]
i installed node with: sudo apt-get install node
and when i do node -v i do not get any results.

**Comment by howardchung** [comment]
yeah, 1.3.10 is really old.  You should be on 3.5.0+.

If node wasn't installed nothing you do should be working.

How did you bootstrap?  `sudo bash init.sh` is supposed to install all of the necessary dependencies.

**Comment by xmindfirex** [comment]
yes that is what i used.
I am following some instructions on how to install node correctly now.
I will look up how to update NPM as well

**Comment by howardchung** [comment]
Couple problems with that:
`sudo apt-get install node` installs the wrong package.  It's an older package that predates Node.js and is NOT what you need.

On Ubuntu, `sudo apt-get install nodejs nodejs-legacy` will install the correct binary and symlink the name `node` to it.  However this isn't the recommended approach because it's probably going to be a very outdated version of Node.

The recommended way to install node is to do it via nvm or n.  The init script uses nvm.

**Comment by howardchung** [comment]
Pull latest master.  I updated the init scripts a few days ago (and moved them under scripts directory)

**Comment by xmindfirex** [comment]
I just pulled everything down in a new environment tonight
I was able to get my NPM updated to 3.8.6
I installed nodejs, now when i try to install the legacy it doesnt appear to work
when i do node-v i get does not exist
if i do nodejs -v i get 4.4.2

**Comment by xmindfirex** [comment]
it looks like the run dev scanner is working now though

**Comment by xmindfirex** [comment]
824 games pulled!  Awesome!

**Comment by xmindfirex** [comment]
So looks like updating the NPM and installing the new NODEJS fixed it.  Cant wait to check out the data tomorrow.  Thanks again.

**Comment by howardchung** [comment]
I'm still surprised that works since behind the scenes it's going to try to use the node executable (which isn't symlinked properly if `node -v` doesn't work).

You can try using n to update your node:
https://github.com/tj/n

Do:
`npm install -g n`
`sudo n stable`

4.4.2 should work fine though.  Production is running on 5.8.0 but I don't think there are any huge things we do with the code that requires it.

**Comment by xmindfirex** [comment]
command n not found

**Comment by howardchung** [comment]
You can try just `n stable`.

Or do the global install with sudo: `sudo npm install -g n`

**Comment by xmindfirex** [comment]
if i do a git add --all; git commit -m "test" does it actually move my files to the actual git?

**Comment by howardchung** [comment]
It will update your local git repository.  You actually won't be able to push directly to the repo since you don't have permissions.  What you should do is fork the repo to your own GitHub account, then update the remote on your local repo to point to your fork.  You can do whatever you want with the fork, then submit a pull request to have the code merged into the main repo when it's ready.

**Comment by xmindfirex** [comment]
got the n stable to work now but not sure what it did

**Comment by howardchung** [comment]
You can check the node version again with `node -v`

**Comment by xmindfirex** [comment]
still says node doesnt exist.

**Comment by howardchung** [comment]
You can find out where n put the binary:
https://github.com/tj/n#binary-usage

`n bin 5.10.11`

Then symlink /usr/bin/node to it (or whatever is in your PATH)

**Comment by xmindfirex** [comment]
I tried a number of commands to get the symlink to work - and found a lot of people with the same problem I was having.  The one that ended up working was:
sudo ln -s /usr/bin/nodejs /usr/sbin/node
Now when i put node -v i get v4.4.2.

My next thing is to limit the data put into the DB from each game while running the scanner.  I only want to get Ranked All-Pick games, and the only fields i want are the 5 radiant heroes, 5 dire heros, game time, winning side, and any MMR or bracket info.

**Comment by xmindfirex** [comment]
i found some relevant data from the scanner output - ranked all pick being game mode 22.  It does not appear to be grabbing any MMR or skill bracket data.  I guess I need to write my own scanner that gets different info about each match?

**Comment by howardchung** [comment]
Re: limiting the data--If you want to eventually merge your code I advise not modifying scanner.  Unless disk space becomes an issue you should be able to develop your functionality with the full data.  If you only want to consider ranked AP matches then you can add that clause to your query.

MMR/skill data is tricky because it's not accessible through the standard match API.  To get MMR data you need to get the `retriever` running with a Steam login (make a new steam account).  Then you need to run the `mmr` service as well which processes MMR requests.  MMR data is stored both in a Redis zset (for fast lookup of current MMR) and in the player_ratings postgres table (which tracks the full rating history for each player).

So to do something like get the average MMR for a match you need to query Redis for the MMRs of the player's involved, then manually compute the average.  In practice the data will not be complete because not all players share MMR publicly.

For development purposes it may be easier to fake a bunch of MMR data.

I am also considering storing match average MMR data permanently in a postgres table.

**Comment by howardchung** [comment]
merge with #855 as highly specific custom queries.
