### ISSUE TITLE
Cant search players info

### ISSUE THREAD

**Issue by nt47** [yasp-dota/yasp#992]
i build it and find nothing about /players
can u open it ?

**Comment by howardchung** [comment]
Need more information.  Did you set up a local dev environment and don't have any player data?  That's expected since your database will be empty.  You can run the `profiler` service if you have some matches (obtained via scanner or request) which will automatically request player data from the Steam API.

**Comment by nt47** [comment]
https://yasp.co/search  
no this method
last is carry

**Comment by howardchung** [comment]
Sounds like you may have an older version.  Pull the latest code from master and try again?

**Comment by nt47** [comment]
thx,off work to test
btw  do u speak Chinese or use QQ ?

**Comment by howardchung** [comment]
Sorry, I don't.  @albertcui does, though!
